import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, BackHandler, Modal, FlatList, Image, Keyboard, KeyboardAvoidingView, Linking, Platform, Pressable, RefreshControl, ScrollView, Switch, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ArrowLeft, Baby, Bell, Check, ChevronRight, CircleUserRound, Feather, Heart, ImagePlus, Leaf, LockKeyhole, MessageCircle, MessagesSquare, MoreHorizontal, Orbit, Send, Settings2, ShieldCheck, ThumbsDown, Users, X } from 'lucide-react-native';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import * as Haptics from 'expo-haptics';
import { useAuth } from '@/store/AuthContext';
import { useThemeColors } from '@/theme/colors';
import { communityRequest as call } from '@/lib/api';
import { APP_MODAL_PROPS, APP_MODAL_OVERLAY } from '@/components/ui/appModal';
import { communityThreads } from '@/lib/communityThreads';
import { CommunityReactions } from '@/components/community/CommunityReactions';
import { useCommunityRealtime } from '@/lib/useCommunityRealtime';
import { useKeyboardMetrics } from '@/lib/useKeyboardHeight';
import { AVATAR_SOURCES, isAvatarId } from '@/constants/avatarAssets';
import type { CommunityIdentityMode } from '@/components/community/CommunityIdentityChoice';
import { CommunityIdentityChoice } from '@/components/community/CommunityIdentityChoice';
import { CommunityJoinForm } from '@/components/community/CommunityJoinForm';
import { CommunityCommentComposer } from '@/components/community/CommunityCommentComposer';
import { CommunityCommentText } from '@/components/community/CommunityCommentText';
import type { CommunityMention } from '@/lib/communityMentions';
import { CommunityNotice } from '@/components/community/CommunityNotice';
import { AnonymousAvatar } from '@/components/community/AnonymousAvatar';
import { requestNotificationPermission, registerPushTokenWithServer } from '@/lib/notifications';

type Content={identityMode?:CommunityIdentityMode;avatarId?:string|null;mentions?:CommunityMention[];id:string;revision:number;body:string;author:string;anonymous:boolean;mine:boolean;status:string;createdAt:string;topic?:string;hasImage:boolean;likes:number;dislikes:number;comments:number;reaction:number;reactions:Record<string,number>;myReaction:string|null;parentId:string|null;replyTo:string|null;liked:boolean};
type Notice={id:string;postId:string;kind:string;readAt:string|null;createdAt:string};
const topics=[['all','ყველა'],['everyday','ყოველდღიურობა'],['cycle','ციკლი'],['pregnancy','ორსულობა'],['wellbeing','თავის მოვლა']];
const topicIcons:Record<string,typeof Heart>={all:MessagesSquare,everyday:Feather,cycle:Orbit,pregnancy:Baby,wellbeing:Leaf};
function TopicIcon({topic,color,size=16}:{topic:string;color:string;size?:number}){const Icon=topicIcons[topic]||Heart;return <Icon size={size} color={color} strokeWidth={1.6}/>;}
const notices:Record<string,string>={like:'შენს პოსტზე ახალი რეაქციაა',dislike:'შენს პოსტზე განსხვავებული აზრია',comment:'შენს პოსტზე ახალი კომენტარია',approved:'შენი ჩანაწერი გამოქვეყნდა',reply:'შენს კომენტარს უპასუხეს',comment_like:'შენი კომენტარი მოიწონეს'};
const rules='ეს ქალების მხარდამჭერი სივრცეა. გაუზიარე გამოცდილება პატივისცემით. დაუშვებელია შეურაცხყოფა, მუქარა, რეკლამა, ინტიმური გამოსახულებები და სხვისი პირადი მონაცემები. გამოცდილება ექიმის რჩევას არ ცვლის. პოსტები და კომენტარები მაშინვე ქვეყნდება. დარღვევის შემთხვევაში გამოიყენე გასაჩივრება — მოდერატორს შეუძლია ჩანაწერის დამალვა და წევრის შეზღუდვა. ანონიმურ რეჟიმში წევრები შენს სახელს ვერ ხედავენ; უსაფრთხოებისა და საჩივრების განხილვისთვის სისტემა ინახავს ანგარიშთან კავშირს. ტექსტში ან ფოტოში თავად ნუ გაამჟღავნებ ვინაობას. სხვა წევრებს შეუძლიათ ეკრანის გადაღება. შენი სამედიცინო ისტორია და ციკლის ჩანაწერები აქ ავტომატურად არასოდეს ქვეყნდება.';
const dateLabel=(value:string)=>{const d=new Date(value);return d.getDate()+' '+['იან','თებ','მარ','აპრ','მაი','ივნ','ივლ','აგვ','სექ','ოქტ','ნოე','დეკ'][d.getMonth()];};
const uuid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});
export default function Community(){const {user}=useAuth();return <Space key={user?.id||'guest'} eligible={user?.gender==='FEMALE'} />;}
function CommunityPhoto({id}:{id:string}){
 const c=useThemeColors(),[uri,setUri]=useState(''),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setUri('');setFailed(false);void call<{uri:string}>(`/posts/${id}/photo`).then(d=>{if(active)setUri(d.uri);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[id,retry]);
 return uri?<Image accessibilityLabel="პოსტის ფოტო" source={{uri}} style={{width:'100%',aspectRatio:1.25,borderRadius:0,backgroundColor:c.bg200}} resizeMode="cover"/>:<Pressable accessibilityRole="button" accessibilityLabel="ფოტოს ხელახლა ჩატვირთვა" onPress={()=>setRetry(n=>n+1)} style={{height:160,borderRadius:0,backgroundColor:c.bg200,alignItems:'center',justifyContent:'center'}}>{failed?<Text style={{color:c.text200}}>ფოტო ვერ ჩაიტვირთა · სცადე ხელახლა</Text>:<ActivityIndicator color={c.primary100}/>}</Pressable>;
}
function Space({eligible}:{eligible:boolean}){
 const c=useThemeColors(),safe=useSafeAreaInsets(),router=useRouter(),params=useLocalSearchParams<{post?:string}>();
 const [member,setMember]=useState<{alias:string;pushEnabled:boolean;defaultIdentity:CommunityIdentityMode;profile:{name:string;avatarId:string|null}}|null>(null),[ready,setReady]=useState(false),[page,setPage]=useState('feed');
 const [reply,setReply]=useState<Content|null>(null);
 const commentInput=useRef<TextInput>(null),detailScroll=useRef<ScrollView>(null),selectedId=useRef<string|null>(null);
 const {height:keyboardHeight}=useKeyboardMetrics();
 const [editing,setEditing]=useState<Content|null>(null);
 const [posts,setPosts]=useState<Content[]>([]),[comments,setComments]=useState<Content[]>([]),[selected,setSelected]=useState<Content|null>(null);
 const [topic,setTopic]=useState('all'),[mine,setMine]=useState(false),[next,setNext]=useState<string|null>(null),[commentNext,setCommentNext]=useState<string|null>(null);
 const [notifications,setNotifications]=useState<Notice[]>([]),[blocks,setBlocks]=useState<{id:string;createdAt:string}[]>([]);
 const [alias,setAlias]=useState(''),[accepted,setAccepted]=useState(false),[body,setBody]=useState(''),[identityMode,setIdentityMode]=useState<CommunityIdentityMode>('nickname'),[draftTopic,setDraftTopic]=useState('everyday'),[photo,setPhoto]=useState<{uri:string;base64:string}|null>(null);
 const anonymous=identityMode==='anonymous';
 const [defaultMode,setDefaultMode]=useState<CommunityIdentityMode>('nickname');
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const draftId=useRef(uuid()),live=useRef(true),feedGen=useRef(0),lock=useRef(false),feedCount=useRef(20);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const [dialog,setDialog]=useState<{title:string;message:string;actions:{text:string;style?:string;onPress?:()=>void}[]}|null>(null);
 const showDialog=(title:string,message:string,actions:{text:string;style?:string;onPress?:()=>void}[])=>setDialog({title,message,actions});
 const text=(value:string,size=14,color=c.text100)=> <Text style={{fontFamily:size>=17?'NotoSansGeorgian_600SemiBold':'NotoSansGeorgian_400Regular',fontSize:size,lineHeight:size*1.55,color}}>{value}</Text>;
 const button=(label:string,action:()=>void,Icon?:any,primary=false,disabled=false)=> <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled||busy} onPress={action} style={{minHeight:46,paddingHorizontal:14,paddingVertical:10,borderRadius:16,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',backgroundColor:primary?'#0F766E':c.bg200,opacity:disabled||busy?0.5:1}}>{Icon&&<Icon size={19} color={primary?'white':c.primary100}/>}<Text style={{fontFamily:'NotoSansGeorgian_600SemiBold',fontSize:13,color:primary?'white':c.text100}}>{label}</Text></Pressable>;
 const run=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(live.current)setError(e instanceof Error?e.message:'ვერ შესრულდა. სცადე ხელახლა.');}finally{lock.current=false;if(live.current)setBusy(false);}};
 feedCount.current=Math.max(20,posts.length);
 const loadFeed=useCallback(async(more=false,silent=false)=>{
  const gen=++feedGen.current;if(!silent)setLoading(true);
  try{const result=await call<{posts:Content[];next:string|null}>(`/posts?topic=${topic}&mine=${mine}&limit=${silent?Math.min(feedCount.current,100):20}${more&&next?'&before='+encodeURIComponent(next):''}`);if(live.current&&gen===feedGen.current){setError('');setPosts(p=>more?[...p,...result.posts.filter(x=>!p.some(y=>y.id===x.id))]:result.posts);setNext(result.next);}}
  catch(e){if(live.current&&gen===feedGen.current){if(!silent||[401,403].includes((e as {status:number}).status))setError((e as Error).message);if([401,403].includes((e as {status:number}).status)){setPosts([]);setComments([]);setSelected(null);setMember(null);setReady(false);}}}finally{if(live.current&&gen===feedGen.current)setLoading(false);}
 },[topic,mine,next]);
 const inbox=async()=>{const data=await call<Notice[]>('/notifications');if(live.current)setNotifications(data);};
 const openPost=async(postId:string)=>{const [p,list]=await Promise.all([call<Content>('/posts/'+postId),call<{comments:Content[];next:string|null}>('/posts/'+postId+'/comments?limit='+Math.min(100,Math.max(30,comments.length)))]);if(!live.current)return;setReply(null);setEditing(null);setSelected(p);setPosts(rows=>rows.map(row=>row.id===p.id?p:row));setComments(list.comments);setCommentNext(list.next);setPage('detail');setBody('');setIdentityMode(p.mine&&p.anonymous?'anonymous':member?.defaultIdentity||'nickname');draftId.current=uuid();};
 useEffect(()=>{if(!eligible){setReady(true);return;}void run(async()=>{const data=await call<{member:typeof member}>('/membership');if(!live.current)return;setMember(data.member);setReady(true);});},[]);
 useEffect(()=>{if(!member)return;void loadFeed();void inbox().catch(()=>{});},[member,topic,mine]);
 useEffect(()=>{if(member&&params.post)void run(()=>openPost(params.post!));},[!!member,params.post]);
 selectedId.current=selected?.id||null;
 const connected=useCommunityRealtime(!!member,async()=>{
  await Promise.all([loadFeed(false,true),inbox()]);
  const postId=selectedId.current;
  if(postId)try{
   const [post,list]=await Promise.all([call<Content>('/posts/'+postId),call<{comments:Content[];next:string|null}>('/posts/'+postId+'/comments?limit='+Math.min(100,Math.max(30,comments.length)))]);
   if(live.current&&selectedId.current===postId){setSelected(post);setComments(list.comments);setCommentNext(list.next);}
  }catch(e){if(live.current&&selectedId.current===postId&&(e as {status?:number}).status===404){setSelected(null);setComments([]);setPage('feed');setMessage('ჩანაწერი აღარ არის ხელმისაწვდომი.');}}
 });
 const choosePhoto=()=>void run(async()=>{
  const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.85});if(picked.canceled)return;
  const asset=picked.assets[0],width=Math.min(asset.width||1200,1200);
  const out=await ImageManipulator.manipulateAsync(asset.uri,[{resize:{width}}],{compress:0.78,format:ImageManipulator.SaveFormat.JPEG,base64:true});
  if(!out.base64||out.base64.length>1500000)throw new Error('ფოტო ძალიან დიდია. აირჩიე უფრო პატარა ფოტო.');setPhoto({uri:out.uri,base64:out.base64});
 });
 const compose=()=>{setReply(null);setEditing(null);setBody('');setPhoto(null);setIdentityMode(member?.defaultIdentity||'nickname');draftId.current=uuid();setPage('compose');setMessage('');};
 const submit=()=>void run(async()=>{if(editing)await call('/posts/'+editing.id,'PATCH',{body,topic:draftTopic,image:photo?.base64||null});else await call('/posts','POST',{body,topic:draftTopic,identityMode,anonymous,requestId:draftId.current,image:photo?.base64||null});setEditing(null);setPage('feed');setBody('');setPhoto(null);setMessage(editing?.status==='HIDDEN'?'ცვლილებები შენახულია. ჩანაწერი კვლავ დამალულია.':'შენი პოსტი გამოქვეყნდა.');await loadFeed();void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(()=>{});});
 const action=async(item:Content,kind:string,what:string,reason?:string)=>{await call(`/${kind}/${item.id}/${what}`,'POST',reason?{reason}:{});if(what==='block'){setPage('feed');await loadFeed();}setMessage(what==='report'?'საჩივარი მიღებულია. მოდერატორი განიხილავს.':'წევრი დაბლოკილია. მის ჩანაწერებს აღარ ნახავ.');};
 const report=(item:Content,kind:string)=>showDialog('შეტყობინება მოდერატორს','აირჩიე მიზეზი',[{text:'შევიწროება',onPress:()=>void run(()=>action(item,kind,'report','harassment'))},{text:'პირადი მონაცემები',onPress:()=>void run(()=>action(item,kind,'report','privacy'))},{text:'სხვა დარღვევა',onPress:()=>void run(()=>action(item,kind,'report','other'))},{text:'გაუქმება',style:'cancel'}]);
 const menu=(item:Content,kind='posts')=>showDialog('ჩანაწერის მართვა',item.anonymous?'ავტორის ვინაობა სხვა წევრებისთვის დაფარულია.':item.author,item.mine?[...(kind==='posts'?[{text:'რედაქტირება',onPress:()=>void run(async()=>{let image=null;if(item.hasImage){const result=await call<{uri:string}>(`/posts/${item.id}/photo`);image={uri:result.uri,base64:result.uri.split(',')[1]};}setEditing(item);setBody(item.body);setDraftTopic(item.topic||'everyday');setIdentityMode(item.anonymous?'anonymous':item.identityMode||'nickname');setPhoto(image);setPage('compose');})}]:[]),{text:'წაშლა',style:'destructive',onPress:()=>showDialog('წაიშალოს ჩანაწერი?','ეს მოქმედება შეუქცევადია.',[{text:'გაუქმება',style:'cancel'},{text:'წაშლა',style:'destructive',onPress:()=>void run(async()=>{await call(`/${kind}/${item.id}`,'DELETE');if(kind==='posts'){setPage('feed');await loadFeed();}else if(selected)await openPost(selected.id);})}])},{text:'გაუქმება',style:'cancel'}]:[{text:'გასაჩივრება',onPress:()=>report(item,kind)},{text:'ავტორის დაბლოკვა',style:'destructive',onPress:()=>void run(()=>action(item,kind,'block'))},{text:'გაუქმება',style:'cancel'}]);
 const avatar=(anon:boolean,alias='',avatarId?:string|null)=> anon?<AnonymousAvatar/>:isAvatarId(avatarId)?<Image source={AVATAR_SOURCES[avatarId]} accessibilityLabel={'პროფილის ავატარი: '+alias} style={{width:34,height:34,borderRadius:17}}/>:<View style={{width:34,height:34,borderRadius:17,backgroundColor:c.accent100,alignItems:'center',justifyContent:'center'}}>{text((alias||'მ').slice(0,1).toUpperCase(),17,c.primary100)}</View>;
 const card=(item:Content,detail=false)=> <View style={{paddingHorizontal:18,paddingTop:16,paddingBottom:6,gap:10}}>
  <View style={{flexDirection:'row',gap:10,alignItems:'center'}}>{avatar(item.anonymous,item.author,item.avatarId)}<View style={{flex:1}}>{text(item.author,14)}{text(dateLabel(item.createdAt)+(item.mine?' · შენი ჩანაწერი':''),11,c.text200)}</View><Pressable accessibilityRole="button" accessibilityLabel="პოსტის მართვა" onPress={()=>menu(item)} style={{padding:10}}><MoreHorizontal size={22} color={c.text200}/></Pressable></View>
  {item.topic&&<View style={{flexDirection:'row',alignItems:'center',gap:6}}><TopicIcon topic={item.topic} color={c.primary100} size={13}/>{text(topics.find(t=>t[0]===item.topic)?.[1]||'',11,c.text200)}</View>}
  <Pressable accessibilityRole="button" onPress={()=>void run(()=>openPost(item.id))}><Text numberOfLines={detail?undefined:7} style={{fontFamily:'NotoSansGeorgian_400Regular',fontSize:15,lineHeight:25,color:c.text100}}>{item.body}</Text></Pressable>
  {item.hasImage&&<View style={{marginHorizontal:-18}}><CommunityPhoto key={item.id+':'+item.revision} id={item.id}/></View>}
  {item.status!=='PUBLISHED'?<View style={{flexDirection:'row',gap:8,alignItems:'center'}}><ShieldCheck size={16} color={c.primary100}/>{text(item.status==='PENDING'?'მოწმდება მოდერატორის მიერ':'დამალულია მოდერაციის მიერ',12,c.text200)}</View>:<CommunityReactions
    counts={item.reactions||{}} selected={item.myReaction} comments={item.comments} disabled={busy}
    onReact={emoji=>void run(async()=>{await call(`/posts/${item.id}/reaction`,'PUT',{emoji});await loadFeed(false,true);if(selected?.id===item.id)setSelected(await call('/posts/'+item.id));})}
    onComment={()=>{if(detail){commentInput.current?.focus();}else void run(()=>openPost(item.id));}}
  />}

 </View>;
 const inputStyle={backgroundColor:c.surface,color:c.text100,borderColor:c.bg300,borderWidth:1,borderRadius:18,padding:16,fontFamily:'NotoSansGeorgian_400Regular',fontSize:15};
 const anonymity=<CommunityIdentityChoice mode={identityMode} fullName={editing?.identityMode==='original'?editing.author:member?.profile?.name||''} avatarId={editing?.identityMode==='original'?editing.avatarId:member?.profile?.avatarId} alias={editing&&!editing.anonymous&&editing.identityMode!=='original'?editing.author:member?.alias||''} locked={!!editing||(page==='detail'&&!!selected?.mine&&selected.anonymous)} onChange={setIdentityMode}/>;
 const back=()=>{setError('');if(page==='feed')router.back();else if((page==='compose'&&(body.trim()||photo))||(page==='detail'&&body.trim()))showDialog('გამოსვლა?','შეუნახავი ტექსტი დაიკარგება.',[{text:'გაგრძელება',style:'cancel'},{text:'გამოსვლა',onPress:()=>{setEditing(null);setPage('feed');setBody('');setPhoto(null);}}]);else{setPage('feed');setBody('');}};
 useEffect(()=>{const listener=BackHandler.addEventListener('hardwareBackPress',()=>{if(dialog){setDialog(null);return true;}if(page!=='feed'){back();return true;}return false;});return()=>listener.remove();},[page,body,photo,dialog]);
 return <KeyboardAvoidingView enabled={!!member} style={{flex:1,width:'100%',maxWidth:760,alignSelf:'center',backgroundColor:c.bg100,paddingTop:safe.top}} behavior={Platform.OS==='ios'?'padding':'height'}>
  <View style={{paddingHorizontal:16,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:10}}><Pressable accessibilityRole="button" accessibilityLabel="უკან" onPress={back} style={{padding:10}}><ArrowLeft color={c.text100} size={23}/></Pressable><View style={{flex:1}}>{text(page==='compose'?(editing?'პოსტის რედაქტირება':'ახალი პოსტი'):page==='inbox'?'შეტყობინებები':page==='settings'?'შენი სივრცე':'ქალების სივრცე',19)}{text(member?(connected?'● განახლდება ავტომატურად':'კავშირი აღდგება ავტომატურად'):'ერთად, ერთმანეთისთვის',11,c.text200)}</View>{member&&page!=='compose'&&!(page==='detail'&&body.trim())&&<><Pressable accessibilityRole="button" accessibilityLabel="შეტყობინებები" onPress={()=>void run(async()=>{await inbox();setPage('inbox');})} style={{padding:10}}><Bell size={22} color={c.primary100}/>{notifications.some(n=>!n.readAt)&&<View style={{position:'absolute',right:8,top:6,width:7,height:7,borderRadius:4,backgroundColor:c.danger}}/>}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="სივრცის პარამეტრები" onPress={()=>void run(async()=>{setBlocks(await call('/blocks'));setAlias(member.alias);setDefaultMode(member.defaultIdentity||'nickname');setPage('settings');})} style={{padding:10}}><Settings2 size={22} color={c.text200}/></Pressable></>}</View>
  {!!error&&<View accessibilityRole="alert" style={{padding:14,backgroundColor:c.dangerBg}}>{text(error,13,c.danger)}{button('ხელახლა ცდა',()=>{setError('');if(member)void loadFeed();else void run(async()=>{const d=await call('/membership');setMember(d.member);setReady(true);});})}</View>}
  {!!message&&<Pressable accessibilityRole="button" onPress={()=>setMessage('')} style={{padding:12,backgroundColor:c.accent100}}>{text(message,12,c.primary100)}</Pressable>}
  {!eligible?<View style={{padding:24}}>{text('ეს სივრცე ხელმისაწვდომია ქალის პროფილის მქონე ანგარიშებისთვის.')}</View>:!ready?(error?null:<ActivityIndicator style={{marginTop:40}} color={c.primary100}/>):!member?<CommunityJoinForm
    alias={alias} onAliasChange={setAlias} accepted={accepted} onAcceptedChange={setAccepted}
    rules={rules} busy={busy}
    onJoin={()=>void run(async()=>{await call('/membership','POST',{alias:alias.trim(),rulesVersion:'2026-09-23'});const result=await call('/membership');setMember(result.member);})}
  />:
  page==='feed'?<FlatList data={posts} keyExtractor={p=>p.id} renderItem={({item})=>card(item)} ItemSeparatorComponent={()=> <View style={{height:1,backgroundColor:c.bg300}}/>} contentContainerStyle={{paddingBottom:safe.bottom+24}} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void loadFeed()} tintColor={c.primary100}/>}
   ListHeaderComponent={<View>
    <View style={{paddingHorizontal:18,paddingVertical:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderColor:c.bg300}}>
     {avatar(member.defaultIdentity==='anonymous',member.defaultIdentity==='original'?member.profile?.name:member.alias,member.defaultIdentity==='original'?member.profile?.avatarId:null)}
     <Pressable accessibilityRole="button" accessibilityLabel="ახალი პოსტის დაწერა" onPress={compose} style={{flex:1,minHeight:44,justifyContent:'center',gap:3}}>{text('რას გაუზიარებ დღეს?',14,c.text200)}{text('შენი სახელით, მეტსახელით ან ანონიმურად',10,c.text200)}</Pressable>
     <Pressable accessibilityRole="button" accessibilityLabel="პოსტის ფოტოს დამატება" onPress={()=>{compose();choosePhoto();}} style={{width:44,height:44,borderRadius:14,backgroundColor:c.accent100,alignItems:'center',justifyContent:'center'}}><ImagePlus size={21} strokeWidth={1.6} color={c.primary100}/></Pressable>
    </View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingHorizontal:18,gap:22}} style={{borderBottomWidth:1,borderColor:c.bg300}}>{topics.map(([key,label])=><Pressable key={key} accessibilityRole="tab" accessibilityState={{selected:topic===key}} onPress={()=>setTopic(key)} style={{minHeight:48,flexDirection:'row',alignItems:'center',gap:6,borderBottomWidth:topic===key?2:0,borderColor:c.primary100}}><TopicIcon topic={key} color={topic===key?c.primary100:c.text200}/><Text style={{fontFamily:topic===key?'NotoSansGeorgian_600SemiBold':'NotoSansGeorgian_400Regular',fontSize:12,color:topic===key?c.text100:c.text200}}>{label}</Text></Pressable>)}</ScrollView>
    <View style={{paddingHorizontal:18,paddingTop:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View style={{flexDirection:'row',alignItems:'center',gap:6}}><MessagesSquare size={14} strokeWidth={1.5} color={c.text200}/>{text(mine?'შენი ჩანაწერები':'ბოლო ამბები',11,c.text200)}</View><Pressable accessibilityRole="button" accessibilityState={{selected:mine}} onPress={()=>setMine(!mine)} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:6}}><CircleUserRound size={16} strokeWidth={1.6} color={c.primary100}/>{text(mine?'ყველას ნახვა':'ჩემი პოსტები',11,c.primary100)}</Pressable></View>
   </View>}

   ListEmptyComponent={!loading?<View style={{alignItems:'center',padding:28,gap:12}}><MessageCircle size={32} color={c.primary100}/>{text('პირველ საუბარს შენ დაიწყებ?',17)}{text('აქ გამოჩნდება გამოქვეყნებული პოსტები და შენი ჩანაწერები.',13,c.text200)}</View>:null}
   ListFooterComponent={next?button('მეტის ნახვა',()=>void loadFeed(true),ChevronRight,false,loading):null}/>:
  page==='compose'?<View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:18,gap:16,paddingBottom:safe.bottom+20}}>{anonymity}<TextInput accessibilityLabel="პოსტის ტექსტი" value={body} onChangeText={setBody} multiline maxLength={3000} placeholder="რისი გაზიარება გინდა?" placeholderTextColor={c.text200} style={[inputStyle,{minHeight:200,borderWidth:0,borderRadius:0,backgroundColor:'transparent',paddingHorizontal:0,textAlignVertical:'top',fontSize:16,lineHeight:26}]}/>{text(`${body.length}/3000`,11,c.text200)}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{topics.slice(1).map(([key,label])=><View key={key}>{button(label,()=>setDraftTopic(key),topicIcons[key],draftTopic===key)}</View>)}</ScrollView>{photo?<View><Image source={{uri:photo.uri}} style={{width:'100%',height:210,borderRadius:20}}/>{button('ფოტოს მოშორება',()=>setPhoto(null),X)}</View>:button('ფოტოს დამატება',choosePhoto,ImagePlus)}{text('პოსტი მაშინვე გამოჩნდება სივრცეში. ფოტოდან მდებარეობის ინფორმაცია ავტომატურად იშლება.',12,c.text200)}</ScrollView><View style={{paddingHorizontal:18,paddingTop:10,paddingBottom:Math.max(safe.bottom,12),borderTopWidth:1,borderColor:c.bg300,backgroundColor:c.surface}}>{button(editing?'ცვლილებების შენახვა':'გამოქვეყნება',submit,Send,true,!body.trim())}</View></View>:
  page==='detail'&&selected?<View style={{flex:1}}>
   <ScrollView ref={detailScroll} keyboardShouldPersistTaps="handled" keyboardDismissMode={Platform.OS==='ios'?'interactive':'on-drag'} contentContainerStyle={{gap:18,paddingBottom:20}}>
    {card(selected,true)}
    <View style={{paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:8}}><MessageCircle size={19} color={c.primary100}/>{text('საუბარი · '+selected.comments,18)}</View>
    {communityThreads(comments).map(({item,depth})=><View key={item.id} style={{marginHorizontal:18,marginLeft:18+depth*12,borderLeftWidth:item.parentId?2:0,borderLeftColor:c.bg300,paddingLeft:item.parentId?12:0,gap:8}}>
     {item.parentId&&text('↳ პასუხი: '+(item.replyTo||'კომენტარი აღარ ჩანს'),11,c.text200)}
     <View style={{flexDirection:'row',gap:10,alignItems:'flex-start'}}>{avatar(item.anonymous,item.author,item.avatarId)}<View style={{flex:1,gap:5}}>
      <View style={{paddingVertical:2,gap:6}}>
       <View style={{flexDirection:'row',alignItems:'center'}}><View style={{flex:1}}>{text(item.author,13)}</View><Pressable accessibilityRole="button" accessibilityLabel="კომენტარის მართვა" onPress={()=>menu(item,'comments')} style={{padding:6}}><MoreHorizontal color={c.text200} size={19}/></Pressable></View>
       <CommunityCommentText body={item.body} mentions={item.mentions} onMention={m=>{const target=comments.find(c=>c.id===m.targetId);showDialog(m.label,'მონაწილე ამ დისკუსიაში',target?[{text:'უპასუხე',onPress:()=>{setReply(target);commentInput.current?.focus();}},{text:'დახურვა'}]:[{text:'დახურვა'}]);}}/>
       {item.status!=='PUBLISHED'&&text('არ არის გამოქვეყნებული',11,c.text200)}
      </View>
      <View style={{flexDirection:'row',alignItems:'center',gap:14}}>{text(dateLabel(item.createdAt),10,c.text200)}
       <Pressable accessibilityRole="button" accessibilityLabel={item.liked?'კომენტარის მოწონების გაუქმება':'კომენტარის მოწონება'} disabled={busy||item.status!=='PUBLISHED'} onPress={()=>void run(async()=>{await call(`/comments/${item.id}/like`,'PUT',{liked:!item.liked});setComments(rows=>rows.map(row=>row.id===item.id?{...row,liked:!item.liked,likes:Math.max(0,row.likes+(item.liked?-1:1))}:row));})} style={{minHeight:40,flexDirection:'row',gap:5,alignItems:'center'}}><Heart size={16} fill={item.liked?c.primary100:'transparent'} color={item.liked?c.primary100:c.text200}/>{text(String(item.likes),11,c.text200)}</Pressable>
       <Pressable accessibilityRole="button" accessibilityLabel={'პასუხი: '+item.author} disabled={item.status!=='PUBLISHED'} onPress={()=>{setReply(item);commentInput.current?.focus();}} style={{minHeight:40,justifyContent:'center'}}>{text('უპასუხე',12,c.primary100)}</Pressable>
      </View>
     </View></View>
    </View>)}
    {commentNext&&button('წინა კომენტარები',()=>void run(async()=>{const d=await call(`/posts/${selected.id}/comments?before=${encodeURIComponent(commentNext)}`);setComments(p=>[...p,...d.comments]);setCommentNext(d.next);}))}
    {comments.length===0&&<View style={{alignItems:'center',padding:20,gap:10}}><MessageCircle size={28} color={c.primary100}/>{text('შენი სიტყვებით დაიწყე საუბარი',16)}{text('გაუზიარე გამოცდილება ან დაუსვი კითხვა.',12,c.text200)}</View>}
   </ScrollView>
   {selected.status==='PUBLISHED'&&<View style={{paddingHorizontal:16,paddingTop:10,paddingBottom:keyboardHeight>24?12:Math.max(safe.bottom,12),borderTopWidth:1,borderColor:c.bg300,backgroundColor:c.surface,gap:8}}>
    {reply&&<View style={{flexDirection:'row',alignItems:'center',gap:10,padding:9,borderRadius:12,backgroundColor:c.bg200}}><View style={{flex:1}}>{text('პასუხობ: '+reply.author,11,c.primary100)}<Text numberOfLines={1} style={{fontFamily:'NotoSansGeorgian_400Regular',fontSize:11,color:c.text200}}>{reply.body}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="პასუხის გაუქმება" onPress={()=>setReply(null)} style={{padding:8}}><X size={18} color={c.text200}/></Pressable></View>}
    <Pressable accessibilityRole="button" accessibilityLabel="კომენტარის ვინაობის არჩევა" onPress={()=>{if(selected.mine&&selected.anonymous)return;Keyboard.dismiss();showDialog('როგორ გამოჩნდები?','პროფილის რეჟიმში საჯაროდ ჩანს მხოლოდ სახელი და ავატარი.',[{text:member.profile?.name+' · პროფილის სახელით',onPress:()=>setIdentityMode('original')},{text:member.alias+' · მეტსახელით',onPress:()=>setIdentityMode('nickname')},{text:'ანონიმურად',onPress:()=>setIdentityMode('anonymous')},{text:'გაუქმება'}]);}} style={{flexDirection:'row',alignItems:'center',gap:7,minHeight:38}}>{avatar(anonymous,identityMode==='original'?member.profile?.name:member.alias,identityMode==='original'?member.profile?.avatarId:null)}<View style={{flex:1}}>{text(anonymous?'კომენტარი ანონიმურად':identityMode==='original'?member.profile?.name||'პროფილის სახელით':member.alias,11,c.primary100)}</View>{!(selected.mine&&selected.anonymous)&&<ChevronRight size={15} color={c.text200}/>}</Pressable>
    <CommunityCommentComposer key={selected.id} postId={selected.id} value={body} onChangeText={setBody} inputRef={commentInput} replying={!!reply} busy={busy} onSend={mentions=>void run(async()=>{await call(`/posts/${selected.id}/comments`,'POST',{body,identityMode,anonymous,mentions,parentId:reply?.id||null,requestId:draftId.current});await openPost(selected.id);})}/>
   </View>}
  </View>:
  page==='inbox'?<FlatList data={notifications} keyExtractor={n=>n.id} contentContainerStyle={{paddingBottom:safe.bottom+20}} ListHeaderComponent={<View style={{paddingHorizontal:18,paddingVertical:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}>{text('შენი აქტივობა',13)}{text(notifications.filter(n=>!n.readAt).length+' წაუკითხავი',11,c.primary100)}</View>} ItemSeparatorComponent={()=> <View style={{height:0.5,backgroundColor:c.bg300,marginLeft:74}}/>} ListEmptyComponent={<View style={{padding:36,gap:12,alignItems:'center'}}><View style={{width:64,height:64,borderRadius:32,backgroundColor:c.accent100,alignItems:'center',justifyContent:'center'}}><Bell color={c.primary100} size={28} strokeWidth={1.5}/></View>{text('შენი საუბრები აქ გაგრძელდება',17)}{text('რეაქციები, კომენტარები და პასუხები — ერთ სივრცეში.',13,c.text200)}</View>} renderItem={({item})=><CommunityNotice item={item} disabled={busy} onPress={()=>void run(async()=>{await call(`/notifications/${item.id}/read`,'PUT');await inbox();await openPost(item.postId);})}/>}/>:
  <ScrollView contentContainerStyle={{padding:20,gap:20,paddingBottom:safe.bottom+20}}><View style={{gap:14}}>{text('შენი საჯარო ვინაობა',18)}{text('აირჩიე, როგორ გამოჩნდები ახალ პოსტებსა და კომენტარებში. თითოეული ჩანაწერის წინ არჩევანის შეცვლაც შეგიძლია.',12,c.text200)}<CommunityIdentityChoice mode={defaultMode} alias={alias||member.alias} fullName={member.profile?.name||''} avatarId={member.profile?.avatarId} locked={false} onChange={setDefaultMode}/>{defaultMode==='nickname'&&<TextInput accessibilityLabel="საჯარო მეტსახელის შეცვლა" value={alias} onChangeText={setAlias} maxLength={40} style={inputStyle}/>}<View style={{flexDirection:'row',alignItems:'flex-start',gap:8}}><ShieldCheck size={17} color={c.primary100}/><View style={{flex:1}}>{text('სამედიცინო ისტორია, ასაკი, მდებარეობა და საკონტაქტო ინფორმაცია არ გამოჩნდება. ძველი ჩანაწერების ვინაობა არ იცვლება.',11,c.text200)}</View></View>{button('არჩევანის შენახვა',()=>void run(async()=>{await call('/membership','POST',{alias:alias.trim(),defaultIdentity:defaultMode,rulesVersion:'2026-09-23'});const result=await call('/membership');setMember(result.member);setMessage('შენი არჩევანი შენახულია.');}),Check,true,alias.trim().length<2)}</View><View style={{flexDirection:'row',alignItems:'center',gap:12}}><Bell color={c.primary100} size={22}/><View style={{flex:1}}>{text('პუშ-შეტყობინებები')}{text('შიგნით შეტყობინებები მაინც შეინახება.',11,c.text200)}</View><Switch accessibilityLabel="სივრცის პუშ შეტყობინებები" value={member.pushEnabled} onValueChange={value=>void run(async()=>{await call('/preferences','PATCH',{pushEnabled:value});setMember({...member!,pushEnabled:value});})}/></View>{button('ტელეფონზე შეტყობინებების ჩართვა',()=>{const permission=requestNotificationPermission();void run(async()=>{const enabled=await permission;if(enabled)await registerPushTokenWithServer({skipPermissionProbe:true});setMessage(enabled?'შეტყობინებების ნებართვა ჩართულია.':'ნებართვა არ არის ჩართული. გადაამოწმე ტელეფონის პარამეტრები.');});},Bell)}{text('ანონიმურობა და წესები',18)}{text(rules,13,c.text200)}{button('support@medicard.ge',()=>void Linking.openURL('mailto:support@medicard.ge'))}{text('დაბლოკილი წევრები',18)}{blocks.length===0&&text('დაბლოკილი წევრები არ გყავს.',13,c.text200)}{blocks.map((b,i)=><View key={b.id} style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}>{text('დაბლოკილი წევრი '+(i+1))}{button('განბლოკვა',()=>void run(async()=>{await call('/blocks/'+b.id,'DELETE');setBlocks(await call('/blocks'));await loadFeed();}))}</View>)}</ScrollView>}
  <Modal visible={!!dialog} {...APP_MODAL_PROPS} onRequestClose={()=>setDialog(null)}><View style={{flex:1,justifyContent:'flex-end'}}><Pressable accessibilityRole="button" accessibilityLabel="დახურვა" onPress={()=>setDialog(null)} style={{position:'absolute',inset:0,backgroundColor:APP_MODAL_OVERLAY}}/><View accessibilityViewIsModal style={{backgroundColor:c.surface,borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:safe.bottom+22,gap:14,width:'100%',maxWidth:760,alignSelf:'center'}}>{text(dialog?.title||'',19)}{text(dialog?.message||'',13,c.text200)}{dialog?.actions.map((a,i)=><Pressable key={i} accessibilityRole="button" onPress={()=>{setDialog(null);a.onPress?.();}} style={{minHeight:48,padding:14,borderRadius:14,backgroundColor:c.bg200}}>{text(a.text,14,a.style==='destructive'?c.danger:c.text100)}</Pressable>)}</View></View></Modal>
  {busy&&<View pointerEvents="none" style={{position:'absolute',top:safe.top+64,right:20,backgroundColor:c.surface,padding:8,borderRadius:20}}><ActivityIndicator color={c.primary100}/></View>}
 </KeyboardAvoidingView>;
}
