import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, BackHandler, Modal, FlatList, Image, KeyboardAvoidingView, Linking, Platform, Pressable, RefreshControl, ScrollView, Switch, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ArrowLeft, Bell, Check, ChevronRight, Feather, Heart, ImagePlus, LockKeyhole, MessageCircle, MoreHorizontal, Send, Settings2, ShieldCheck, ThumbsDown, Users, X } from 'lucide-react-native';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import * as Haptics from 'expo-haptics';
import { useAuth } from '@/store/AuthContext';
import { useThemeColors } from '@/theme/colors';
import { communityRequest as call } from '@/lib/api';
import { APP_MODAL_PROPS, APP_MODAL_OVERLAY } from '@/components/ui/appModal';
import { requestNotificationPermission, registerPushTokenWithServer } from '@/lib/notifications';

type Content={id:string;revision:number;body:string;author:string;anonymous:boolean;mine:boolean;status:string;createdAt:string;topic?:string;hasImage:boolean;likes:number;dislikes:number;comments:number;reaction:number};
type Notice={id:string;postId:string;kind:string;readAt:string|null;createdAt:string};
const topics=[['all','ყველა'],['everyday','ყოველდღიურობა'],['cycle','ციკლი'],['pregnancy','ორსულობა'],['wellbeing','თავის მოვლა']];
const notices:Record<string,string>={like:'შენს პოსტს ახალი მოწონება აქვს',dislike:'შენს პოსტზე განსხვავებული აზრია',comment:'შენს პოსტზე ახალი კომენტარია',approved:'შენი ჩანაწერი გამოქვეყნდა'};
const rules='ეს ქალების მხარდამჭერი სივრცეა. გაუზიარე გამოცდილება პატივისცემით. დაუშვებელია შეურაცხყოფა, მუქარა, რეკლამა, ინტიმური გამოსახულებები და სხვისი პირადი მონაცემები. გამოცდილება ექიმის რჩევას არ ცვლის. პოსტებსა და კომენტარებს გამოქვეყნებამდე მოდერატორი ამოწმებს. ანონიმურ რეჟიმში წევრები შენს სახელს ვერ ხედავენ; უსაფრთხოებისა და საჩივრების განხილვისთვის სისტემა ინახავს ანგარიშთან კავშირს. ტექსტში ან ფოტოში თავად ნუ გაამჟღავნებ ვინაობას. სხვა წევრებს შეუძლიათ ეკრანის გადაღება. შენი სამედიცინო ისტორია და ციკლის ჩანაწერები აქ ავტომატურად არასოდეს ქვეყნდება.';
const dateLabel=(value:string)=>{const d=new Date(value);return d.getDate()+' '+['იან','თებ','მარ','აპრ','მაი','ივნ','ივლ','აგვ','სექ','ოქტ','ნოე','დეკ'][d.getMonth()];};
const uuid=()=> 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});
export default function Community(){const {user}=useAuth();return <Space key={user?.id||'guest'} eligible={user?.gender==='FEMALE'} />;}
function CommunityPhoto({id}:{id:string}){
 const c=useThemeColors(),[uri,setUri]=useState(''),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setUri('');setFailed(false);void call<{uri:string}>(`/posts/${id}/photo`).then(d=>{if(active)setUri(d.uri);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[id,retry]);
 return uri?<Image accessibilityLabel="პოსტის ფოტო" source={{uri}} style={{width:'100%',aspectRatio:1.25,borderRadius:16,backgroundColor:c.bg200}} resizeMode="cover"/>:<Pressable accessibilityRole="button" accessibilityLabel="ფოტოს ხელახლა ჩატვირთვა" onPress={()=>setRetry(n=>n+1)} style={{height:160,borderRadius:16,backgroundColor:c.bg200,alignItems:'center',justifyContent:'center'}}>{failed?<Text style={{color:c.text200}}>ფოტო ვერ ჩაიტვირთა · სცადე ხელახლა</Text>:<ActivityIndicator color={c.primary100}/>}</Pressable>;
}
function Space({eligible}:{eligible:boolean}){
 const c=useThemeColors(),safe=useSafeAreaInsets(),router=useRouter(),params=useLocalSearchParams<{post?:string}>();
 const [member,setMember]=useState<{alias:string;pushEnabled:boolean}|null>(null),[ready,setReady]=useState(false),[page,setPage]=useState('feed');
 const [editing,setEditing]=useState<Content|null>(null);
 const [posts,setPosts]=useState<Content[]>([]),[comments,setComments]=useState<Content[]>([]),[selected,setSelected]=useState<Content|null>(null);
 const [topic,setTopic]=useState('all'),[mine,setMine]=useState(false),[next,setNext]=useState<string|null>(null),[commentNext,setCommentNext]=useState<string|null>(null);
 const [notifications,setNotifications]=useState<Notice[]>([]),[blocks,setBlocks]=useState<{id:string;createdAt:string}[]>([]);
 const [alias,setAlias]=useState(''),[accepted,setAccepted]=useState(false),[body,setBody]=useState(''),[anonymous,setAnonymous]=useState(true),[draftTopic,setDraftTopic]=useState('everyday'),[photo,setPhoto]=useState<{uri:string;base64:string}|null>(null);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
 const draftId=useRef(uuid()),live=useRef(true),feedGen=useRef(0),lock=useRef(false);
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 const [dialog,setDialog]=useState<{title:string;message:string;actions:{text:string;style?:string;onPress?:()=>void}[]}|null>(null);
 const showDialog=(title:string,message:string,actions:{text:string;style?:string;onPress?:()=>void}[])=>setDialog({title,message,actions});
 const text=(value:string,size=14,color=c.text100)=> <Text style={{fontFamily:size>=17?'NotoSansGeorgian_600SemiBold':'NotoSansGeorgian_400Regular',fontSize:size,lineHeight:size*1.55,color}}>{value}</Text>;
 const button=(label:string,action:()=>void,Icon?:any,primary=false,disabled=false)=> <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled||busy} onPress={action} style={{minHeight:46,paddingHorizontal:14,paddingVertical:10,borderRadius:16,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',backgroundColor:primary?'#0F766E':c.bg200,opacity:disabled||busy?0.5:1}}>{Icon&&<Icon size={19} color={primary?'white':c.primary100}/>}<Text style={{fontFamily:'NotoSansGeorgian_600SemiBold',fontSize:13,color:primary?'white':c.text100}}>{label}</Text></Pressable>;
 const run=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){if(live.current)setError(e instanceof Error?e.message:'ვერ შესრულდა. სცადე ხელახლა.');}finally{lock.current=false;if(live.current)setBusy(false);}};
 const loadFeed=useCallback(async(more=false)=>{
  const gen=++feedGen.current;setLoading(true);
  try{const result=await call<{posts:Content[];next:string|null}>(`/posts?topic=${topic}&mine=${mine}${more&&next?'&before='+encodeURIComponent(next):''}`);if(live.current&&gen===feedGen.current){setPosts(p=>more?[...p,...result.posts.filter(x=>!p.some(y=>y.id===x.id))]:result.posts);setNext(result.next);}}
  catch(e){if(live.current)setError((e as Error).message);}finally{if(live.current&&gen===feedGen.current)setLoading(false);}
 },[topic,mine,next]);
 const inbox=async()=>{const data=await call<Notice[]>('/notifications');if(live.current)setNotifications(data);};
 const openPost=async(postId:string)=>{const [p,list]=await Promise.all([call<Content>('/posts/'+postId),call<{comments:Content[];next:string|null}>('/posts/'+postId+'/comments')]);if(!live.current)return;setEditing(null);setSelected(p);setPosts(rows=>rows.map(row=>row.id===p.id?p:row));setComments(list.comments);setCommentNext(list.next);setPage('detail');setBody('');setAnonymous(true);draftId.current=uuid();};
 useEffect(()=>{if(!eligible){setReady(true);return;}void run(async()=>{const data=await call<{member:typeof member}>('/membership');if(!live.current)return;setMember(data.member);setReady(true);});},[]);
 useEffect(()=>{if(!member)return;void loadFeed();void inbox().catch(()=>{});},[member,topic,mine]);
 useEffect(()=>{if(member&&params.post)void run(()=>openPost(params.post!));},[!!member,params.post]);
 useEffect(()=>{if(!member)return;const timer=setInterval(()=>{if(AppState.currentState==='active')void inbox().catch(()=>{});},30000);return()=>clearInterval(timer);},[member]);
 const choosePhoto=()=>void run(async()=>{
  const picked=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.85});if(picked.canceled)return;
  const asset=picked.assets[0],width=Math.min(asset.width||1200,1200);
  const out=await ImageManipulator.manipulateAsync(asset.uri,[{resize:{width}}],{compress:0.78,format:ImageManipulator.SaveFormat.JPEG,base64:true});
  if(!out.base64||out.base64.length>1500000)throw new Error('ფოტო ძალიან დიდია. აირჩიე უფრო პატარა ფოტო.');setPhoto({uri:out.uri,base64:out.base64});
 });
 const compose=()=>{setEditing(null);setBody('');setPhoto(null);setAnonymous(true);draftId.current=uuid();setPage('compose');setMessage('');};
 const submit=()=>void run(async()=>{if(editing)await call('/posts/'+editing.id,'PATCH',{body,topic:draftTopic,image:photo?.base64||null});else await call('/posts','POST',{body,topic:draftTopic,anonymous,requestId:draftId.current,image:photo?.base64||null});setEditing(null);setEditing(null);setPage('feed');setBody('');setPhoto(null);setMessage('პოსტი შენახულია — გამოჩნდება მოდერაციის შემდეგ.');await loadFeed();void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(()=>{});});
 const action=async(item:Content,kind:string,what:string,reason?:string)=>{await call(`/${kind}/${item.id}/${what}`,'POST',reason?{reason}:{});if(what==='block'){setPage('feed');await loadFeed();}setMessage(what==='report'?'საჩივარი მიღებულია. მოდერატორი განიხილავს.':'წევრი დაბლოკილია. მის ჩანაწერებს აღარ ნახავ.');};
 const report=(item:Content,kind:string)=>showDialog('შეტყობინება მოდერატორს','აირჩიე მიზეზი',[{text:'შევიწროება',onPress:()=>void run(()=>action(item,kind,'report','harassment'))},{text:'პირადი მონაცემები',onPress:()=>void run(()=>action(item,kind,'report','privacy'))},{text:'სხვა დარღვევა',onPress:()=>void run(()=>action(item,kind,'report','other'))},{text:'გაუქმება',style:'cancel'}]);
 const menu=(item:Content,kind='posts')=>showDialog('ჩანაწერის მართვა',item.anonymous?'ავტორის ვინაობა სხვა წევრებისთვის დაფარულია.':item.author,item.mine?[...(kind==='posts'?[{text:'რედაქტირება',onPress:()=>void run(async()=>{let image=null;if(item.hasImage){const result=await call<{uri:string}>(`/posts/${item.id}/photo`);image={uri:result.uri,base64:result.uri.split(',')[1]};}setEditing(item);setBody(item.body);setDraftTopic(item.topic||'everyday');setAnonymous(item.anonymous);setPhoto(image);setPage('compose');})}]:[]),{text:'წაშლა',style:'destructive',onPress:()=>showDialog('წაიშალოს ჩანაწერი?','ეს მოქმედება შეუქცევადია.',[{text:'გაუქმება',style:'cancel'},{text:'წაშლა',style:'destructive',onPress:()=>void run(async()=>{await call(`/${kind}/${item.id}`,'DELETE');if(kind==='posts'){setPage('feed');await loadFeed();}else if(selected)await openPost(selected.id);})}])},{text:'გაუქმება',style:'cancel'}]:[{text:'გასაჩივრება',onPress:()=>report(item,kind)},{text:'ავტორის დაბლოკვა',style:'destructive',onPress:()=>void run(()=>action(item,kind,'block'))},{text:'გაუქმება',style:'cancel'}]);
 const avatar=(anon:boolean)=> <View style={{width:40,height:40,borderRadius:15,backgroundColor:c.accent100,alignItems:'center',justifyContent:'center'}}>{anon?<LockKeyhole size={18} color={c.primary100}/>:<Users size={19} color={c.primary100}/>}</View>;
 const card=(item:Content,detail=false)=> <View style={{backgroundColor:c.surface,borderRadius:24,padding:18,gap:14,borderWidth:1,borderColor:c.bg300}}>
  <View style={{flexDirection:'row',gap:10,alignItems:'center'}}>{avatar(item.anonymous)}<View style={{flex:1}}>{text(item.author,14)}{text(dateLabel(item.createdAt)+(item.mine?' · შენი ჩანაწერი':''),11,c.text200)}</View><Pressable accessibilityRole="button" accessibilityLabel="პოსტის მართვა" onPress={()=>menu(item)} style={{padding:10}}><MoreHorizontal size={22} color={c.text200}/></Pressable></View>
  {item.topic&&text(topics.find(t=>t[0]===item.topic)?.[1]||'',11,c.primary100)}
  <Pressable accessibilityRole="button" onPress={()=>void run(()=>openPost(item.id))}><Text numberOfLines={detail?undefined:7} style={{fontFamily:'NotoSansGeorgian_400Regular',fontSize:15,lineHeight:25,color:c.text100}}>{item.body}</Text></Pressable>
  {item.hasImage&&<CommunityPhoto key={item.id+':'+item.revision} id={item.id}/>}
  {item.status!=='PUBLISHED'?<View style={{flexDirection:'row',gap:8,alignItems:'center'}}><ShieldCheck size={16} color={c.primary100}/>{text(item.status==='PENDING'?'მოწმდება მოდერატორის მიერ':'დამალულია მოდერაციის მიერ',12,c.text200)}</View>:<View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>
   {button(String(item.likes),()=>void run(async()=>{await call(`/posts/${item.id}/reaction`,'PUT',{value:item.reaction===1?0:1});await loadFeed();if(selected?.id===item.id)setSelected(await call('/posts/'+item.id));}),Heart,item.reaction===1)}
   {button(String(item.dislikes),()=>void run(async()=>{await call(`/posts/${item.id}/reaction`,'PUT',{value:item.reaction===-1?0:-1});await loadFeed();if(selected?.id===item.id)setSelected(await call('/posts/'+item.id));}),ThumbsDown,item.reaction===-1)}
   {button(detail?'კომენტარები':String(item.comments),()=>void run(()=>openPost(item.id)),MessageCircle)}
  </View>}
 </View>;
 const inputStyle={backgroundColor:c.surface,color:c.text100,borderColor:c.bg300,borderWidth:1,borderRadius:18,padding:16,fontFamily:'NotoSansGeorgian_400Regular',fontSize:15};
 const anonymity=<View style={{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12}}><LockKeyhole color={c.primary100} size={21}/><View style={{flex:1}}>{text('ანონიმურად',14)}{text(anonymous?'შენი მეტსახელი არ გამოჩნდება':'გამოჩნდება: '+member?.alias,11,c.text200)}</View><Switch accessibilityLabel="ანონიმური გამოქვეყნება" value={anonymous} disabled={!!editing||(page==='detail'&&!!selected?.mine&&selected.anonymous)} onValueChange={setAnonymous} trackColor={{true:'#0D9488',false:c.bg300}}/></View>;
 const back=()=>{setError('');if(page==='feed')router.back();else if((page==='compose'&&(body.trim()||photo))||(page==='detail'&&body.trim()))showDialog('გამოსვლა?','შეუნახავი ტექსტი დაიკარგება.',[{text:'გაგრძელება',style:'cancel'},{text:'გამოსვლა',onPress:()=>{setEditing(null);setPage('feed');setBody('');setPhoto(null);}}]);else{setPage('feed');setBody('');}};
 useEffect(()=>{const listener=BackHandler.addEventListener('hardwareBackPress',()=>{if(dialog){setDialog(null);return true;}if(page!=='feed'){back();return true;}return false;});return()=>listener.remove();},[page,body,photo,dialog]);
 return <KeyboardAvoidingView style={{flex:1,width:'100%',maxWidth:760,alignSelf:'center',backgroundColor:c.bg100,paddingTop:safe.top}} behavior={Platform.OS==='ios'?'padding':'height'}>
  <View style={{paddingHorizontal:16,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:10}}><Pressable accessibilityRole="button" accessibilityLabel="უკან" onPress={back} style={{padding:10}}><ArrowLeft color={c.text100} size={23}/></Pressable><View style={{flex:1}}>{text(page==='compose'?(editing?'პოსტის რედაქტირება':'ახალი პოსტი'):page==='inbox'?'შეტყობინებები':page==='settings'?'შენი სივრცე':'ქალების სივრცე',19)}{text('ერთად, ერთმანეთისთვის',11,c.text200)}</View>{member&&page!=='compose'&&!(page==='detail'&&body.trim())&&<><Pressable accessibilityRole="button" accessibilityLabel="შეტყობინებები" onPress={()=>void run(async()=>{await inbox();setPage('inbox');})} style={{padding:10}}><Bell size={22} color={c.primary100}/>{notifications.some(n=>!n.readAt)&&<View style={{position:'absolute',right:8,top:6,width:7,height:7,borderRadius:4,backgroundColor:c.danger}}/>}</Pressable><Pressable accessibilityRole="button" accessibilityLabel="სივრცის პარამეტრები" onPress={()=>void run(async()=>{setBlocks(await call('/blocks'));setAlias(member.alias);setPage('settings');})} style={{padding:10}}><Settings2 size={22} color={c.text200}/></Pressable></>}</View>
  {!!error&&<View accessibilityRole="alert" style={{padding:14,backgroundColor:c.dangerBg}}>{text(error,13,c.danger)}{button('ხელახლა ცდა',()=>{setError('');if(member)void loadFeed();else void run(async()=>{const d=await call('/membership');setMember(d.member);setReady(true);});})}</View>}
  {!!message&&<Pressable accessibilityRole="button" onPress={()=>setMessage('')} style={{padding:12,backgroundColor:c.accent100}}>{text(message,12,c.primary100)}</Pressable>}
  {!eligible?<View style={{padding:24}}>{text('ეს სივრცე ხელმისაწვდომია ქალის პროფილის მქონე ანგარიშებისთვის.')}</View>:!ready?(error?null:<ActivityIndicator style={{marginTop:40}} color={c.primary100}/>):!member?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,gap:20,paddingBottom:safe.bottom+24}}><ShieldCheck size={42} color={c.primary100}/>{text('სივრცე, სადაც მოგისმენენ',25)}{text(rules,14,c.text200)}<TextInput accessibilityLabel="საჯარო მეტსახელი" placeholder="აირჩიე საჯარო მეტსახელი" placeholderTextColor={c.text200} value={alias} onChangeText={setAlias} maxLength={40} style={inputStyle}/><View style={{flexDirection:'row',gap:12,alignItems:'center'}}><Switch accessibilityLabel="ვეთანხმები სივრცის წესებს" value={accepted} onValueChange={setAccepted}/><View style={{flex:1}}>{text('გავეცანი წესებს და ანონიმურობის პირობებს',12)}</View></View>{button('შემოუერთდი სივრცეს',()=>void run(async()=>{await call('/membership','POST',{alias,rulesVersion:'2026-09-23'});setMember({alias,pushEnabled:true});}),Users,true,!accepted||alias.trim().length<2)}{button('დაგვიკავშირდი',()=>void Linking.openURL('mailto:support@medicard.ge'))}</ScrollView>:
  page==='feed'?<FlatList data={posts} keyExtractor={p=>p.id} renderItem={({item})=>card(item)} ItemSeparatorComponent={()=> <View style={{height:14}}/>} contentContainerStyle={{padding:16,paddingBottom:safe.bottom+24}} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void loadFeed()} tintColor={c.primary100}/>}
   ListHeaderComponent={<View style={{gap:16,marginBottom:18}}><View style={{backgroundColor:c.accent100,padding:22,borderRadius:26,gap:10}}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Feather size={21} color={c.primary100}/>{text('შენი ამბავი მნიშვნელოვანია',20,c.primary100)}</View>{text('კითხვა, პატარა გამარჯვება თუ რთული დღე — აქ შეგიძლია გააზიარო.',13,c.text200)}{button('რას გაუზიარებ დღეს?',compose,Feather,true)}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{topics.map(([key,label])=><View key={key}>{button(label,()=>setTopic(key),undefined,topic===key)}</View>)}</ScrollView><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}>{text('საუბრები',17)}{button(mine?'ყველას პოსტები':'ჩემი პოსტები',()=>setMine(!mine))}</View></View>}
   ListEmptyComponent={!loading?<View style={{alignItems:'center',padding:28,gap:12}}><MessageCircle size={32} color={c.primary100}/>{text('პირველ საუბარს შენ დაიწყებ?',17)}{text('აქ გამოჩნდება გამოქვეყნებული პოსტები და შენი ჩანაწერები.',13,c.text200)}</View>:null}
   ListFooterComponent={next?button('მეტის ნახვა',()=>void loadFeed(true),ChevronRight,false,loading):null}/>:
  page==='compose'?<View style={{flex:1}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:18,gap:16,paddingBottom:safe.bottom+20}}>{anonymity}<TextInput accessibilityLabel="პოსტის ტექსტი" value={body} onChangeText={setBody} multiline maxLength={3000} placeholder="რისი გაზიარება გინდა?" placeholderTextColor={c.text200} style={[inputStyle,{minHeight:180,textAlignVertical:'top'}]}/>{text(`${body.length}/3000`,11,c.text200)}<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{topics.slice(1).map(([key,label])=><View key={key}>{button(label,()=>setDraftTopic(key),undefined,draftTopic===key)}</View>)}</ScrollView>{photo?<View><Image source={{uri:photo.uri}} style={{width:'100%',height:210,borderRadius:20}}/>{button('ფოტოს მოშორება',()=>setPhoto(null),X)}</View>:button('ფოტოს დამატება',choosePhoto,ImagePlus)}{text('გამოქვეყნდება მოდერაციის შემდეგ. ფოტოდან ავტომატურად იშლება მდებარეობის მეტამონაცემები.',12,c.text200)}</ScrollView><View style={{paddingHorizontal:18,paddingTop:10,paddingBottom:Math.max(safe.bottom,12),borderTopWidth:1,borderColor:c.bg300,backgroundColor:c.surface}}>{button('გაგზავნა მოდერაციაზე',submit,Send,true,!body.trim())}</View></View>:
  page==='detail'&&selected?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:16,gap:16,paddingBottom:safe.bottom+20}}>{card(selected,true)}{text('კომენტარები',18)}{comments.map(item=><View key={item.id} style={{backgroundColor:c.surface,padding:16,borderRadius:20,gap:8}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}>{avatar(item.anonymous)}<View style={{flex:1}}>{text(item.author,13)}</View><Pressable accessibilityRole="button" accessibilityLabel="კომენტარის მართვა" onPress={()=>menu(item,'comments')} style={{padding:10}}><MoreHorizontal color={c.text200} size={20}/></Pressable></View>{text(item.body)}{item.status!=='PUBLISHED'&&text('მოწმდება',11,c.text200)}</View>)}{commentNext&&button('წინა კომენტარები',()=>void run(async()=>{const d=await call(`/posts/${selected.id}/comments?before=${encodeURIComponent(commentNext)}`);setComments(p=>[...p,...d.comments]);setCommentNext(d.next);}))}{comments.length===0&&text('ჯერ კომენტარი არ არის. მოუსმინე და გაუზიარე შენი გამოცდილება.',13,c.text200)}{selected.status==='PUBLISHED'&&<>{anonymity}<TextInput accessibilityLabel="კომენტარი" placeholder="დაწერე კომენტარი…" placeholderTextColor={c.text200} value={body} onChangeText={setBody} multiline maxLength={1500} style={[inputStyle,{minHeight:85}]}/>{button('კომენტარის გაგზავნა',()=>void run(async()=>{await call(`/posts/${selected.id}/comments`,'POST',{body,anonymous,requestId:draftId.current});await openPost(selected.id);setMessage('კომენტარი შენახულია და მოწმდება.');}),Send,true,!body.trim())}</>}</ScrollView>:
  page==='inbox'?<FlatList data={notifications} keyExtractor={n=>n.id} contentContainerStyle={{padding:16,gap:10,paddingBottom:safe.bottom+20}} ListEmptyComponent={<View style={{padding:30,gap:12,alignItems:'center'}}><Bell color={c.primary100} size={34}/>{text('შეტყობინებები აქ დაგხვდება',17)}{text('როცა შენს პოსტს გამოეხმაურებიან, შეგატყობინებთ.',13,c.text200)}</View>} renderItem={({item})=><Pressable accessibilityRole="button" onPress={()=>void run(async()=>{await call(`/notifications/${item.id}/read`,'PUT');await inbox();await openPost(item.postId);})} style={{padding:18,borderRadius:20,backgroundColor:item.readAt?c.surface:c.accent100,gap:8}}>{text(notices[item.kind]||'ახალი აქტივობა',14)}{text(dateLabel(item.createdAt)+' · '+new Date(item.createdAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),11,c.text200)}</Pressable>}/>:
  <ScrollView contentContainerStyle={{padding:20,gap:20,paddingBottom:safe.bottom+20}}>{text('შენი საჯარო მეტსახელი',18)}<TextInput accessibilityLabel="საჯარო მეტსახელის შეცვლა" value={alias} onChangeText={setAlias} maxLength={40} style={inputStyle}/>{button('მეტსახელის შენახვა',()=>void run(async()=>{await call('/membership','POST',{alias,rulesVersion:'2026-09-23'});setMember({...member,alias});setMessage('მეტსახელი შენახულია.');}),Check,false,alias.trim().length<2)}<View style={{flexDirection:'row',alignItems:'center',gap:12}}><Bell color={c.primary100} size={22}/><View style={{flex:1}}>{text('პუშ-შეტყობინებები')}{text('შიგნით შეტყობინებები მაინც შეინახება.',11,c.text200)}</View><Switch accessibilityLabel="სივრცის პუშ შეტყობინებები" value={member.pushEnabled} onValueChange={value=>void run(async()=>{await call('/preferences','PATCH',{pushEnabled:value});setMember({...member,pushEnabled:value});})}/></View>{button('ტელეფონზე შეტყობინებების ჩართვა',()=>{const permission=requestNotificationPermission();void run(async()=>{const enabled=await permission;if(enabled)await registerPushTokenWithServer({skipPermissionProbe:true});setMessage(enabled?'შეტყობინებების ნებართვა ჩართულია.':'ნებართვა არ არის ჩართული. გადაამოწმე ტელეფონის პარამეტრები.');});},Bell)}{text('ანონიმურობა და წესები',18)}{text(rules,13,c.text200)}{button('support@medicard.ge',()=>void Linking.openURL('mailto:support@medicard.ge'))}{text('დაბლოკილი წევრები',18)}{blocks.length===0&&text('დაბლოკილი წევრები არ გყავს.',13,c.text200)}{blocks.map((b,i)=><View key={b.id} style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}>{text('დაბლოკილი წევრი '+(i+1))}{button('განბლოკვა',()=>void run(async()=>{await call('/blocks/'+b.id,'DELETE');setBlocks(await call('/blocks'));await loadFeed();}))}</View>)}</ScrollView>}
  <Modal visible={!!dialog} {...APP_MODAL_PROPS} onRequestClose={()=>setDialog(null)}><View style={{flex:1,justifyContent:'flex-end'}}><Pressable accessibilityRole="button" accessibilityLabel="დახურვა" onPress={()=>setDialog(null)} style={{position:'absolute',inset:0,backgroundColor:APP_MODAL_OVERLAY}}/><View accessibilityViewIsModal style={{backgroundColor:c.surface,borderTopLeftRadius:28,borderTopRightRadius:28,padding:22,paddingBottom:safe.bottom+22,gap:14,width:'100%',maxWidth:760,alignSelf:'center'}}>{text(dialog?.title||'',19)}{text(dialog?.message||'',13,c.text200)}{dialog?.actions.map((a,i)=><Pressable key={i} accessibilityRole="button" onPress={()=>{setDialog(null);a.onPress?.();}} style={{minHeight:48,padding:14,borderRadius:14,backgroundColor:c.bg200}}>{text(a.text,14,a.style==='destructive'?c.danger:c.text100)}</Pressable>)}</View></View></Modal>
  {busy&&<View pointerEvents="none" style={{position:'absolute',top:safe.top+64,right:20,backgroundColor:c.surface,padding:8,borderRadius:20}}><ActivityIndicator color={c.primary100}/></View>}
 </KeyboardAvoidingView>;
}
