// Generated by brand/medirun/export_art.py from fal.ai renders — do not edit by hand.
// 3D artwork for Pets, Medi Quest, onboarding goals, empty states and referral (same style as MEDIRUN).
import type {ImageSourcePropType} from 'react-native';

export const PETS_ART={
  allergy: require('../../assets/art/pets/allergy.png'),
  bird: require('../../assets/art/pets/bird.png'),
  calendar: require('../../assets/art/pets/calendar.png'),
  care_deworm: require('../../assets/art/pets/care_deworm.png'),
  care_flea: require('../../assets/art/pets/care_flea.png'),
  care_med: require('../../assets/art/pets/care_med.png'),
  care_other: require('../../assets/art/pets/care_other.png'),
  care_vaccine: require('../../assets/art/pets/care_vaccine.png'),
  cat: require('../../assets/art/pets/cat.png'),
  condition: require('../../assets/art/pets/condition.png'),
  dog: require('../../assets/art/pets/dog.png'),
  empty: require('../../assets/art/pets/empty.png'),
  fish: require('../../assets/art/pets/fish.png'),
  horse: require('../../assets/art/pets/horse.png'),
  other: require('../../assets/art/pets/other.png'),
  products: require('../../assets/art/pets/products.png'),
  rabbit: require('../../assets/art/pets/rabbit.png'),
  reptile: require('../../assets/art/pets/reptile.png'),
  rodent: require('../../assets/art/pets/rodent.png'),
  vet: require('../../assets/art/pets/vet.png'),
  weight: require('../../assets/art/pets/weight.png'),
} satisfies Record<string,ImageSourcePropType>;

export const QUEST_ART={
  calendar: require('../../assets/art/quest/calendar.png'),
  coins: require('../../assets/art/quest/coins.png'),
  comeback: require('../../assets/art/quest/comeback.png'),
  dec_frame: require('../../assets/art/quest/dec_frame.png'),
  dec_lamp: require('../../assets/art/quest/dec_lamp.png'),
  dec_plant: require('../../assets/art/quest/dec_plant.png'),
  dec_shelf: require('../../assets/art/quest/dec_shelf.png'),
  dec_window: require('../../assets/art/quest/dec_window.png'),
  eq_badge: require('../../assets/art/quest/eq_badge.png'),
  eq_curious: require('../../assets/art/quest/eq_curious.png'),
  eq_focused: require('../../assets/art/quest/eq_focused.png'),
  eq_orbit: require('../../assets/art/quest/eq_orbit.png'),
  eq_pin: require('../../assets/art/quest/eq_pin.png'),
  eq_proud: require('../../assets/art/quest/eq_proud.png'),
  eq_resting: require('../../assets/art/quest/eq_resting.png'),
  eq_scarf: require('../../assets/art/quest/eq_scarf.png'),
  eq_visor: require('../../assets/art/quest/eq_visor.png'),
  eq_wave: require('../../assets/art/quest/eq_wave.png'),
  history: require('../../assets/art/quest/history.png'),
  hydration: require('../../assets/art/quest/hydration.png'),
  ledger_quest: require('../../assets/art/quest/ledger_quest.png'),
  level: require('../../assets/art/quest/level.png'),
  medi: require('../../assets/art/quest/medi.png'),
  movement: require('../../assets/art/quest/movement.png'),
  reward_coupon: require('../../assets/art/quest/reward_coupon.png'),
  reward_premium: require('../../assets/art/quest/reward_premium.png'),
  reward_style: require('../../assets/art/quest/reward_style.png'),
  reward_theme: require('../../assets/art/quest/reward_theme.png'),
  reward_voucher: require('../../assets/art/quest/reward_voucher.png'),
  secret: require('../../assets/art/quest/secret.png'),
  special: require('../../assets/art/quest/special.png'),
  wallet: require('../../assets/art/quest/wallet.png'),
  weekly: require('../../assets/art/quest/weekly.png'),
  xp: require('../../assets/art/quest/xp.png'),
} satisfies Record<string,ImageSourcePropType>;

export const GOAL_ART={
  cycle: require('../../assets/art/goal/cycle.png'),
  general: require('../../assets/art/goal/general.png'),
  meds: require('../../assets/art/goal/meds.png'),
  nutrition: require('../../assets/art/goal/nutrition.png'),
} satisfies Record<string,ImageSourcePropType>;

export const EMPTY_ART={
  coach: require('../../assets/art/empty/coach.png'),
  community: require('../../assets/art/empty/community.png'),
  diary: require('../../assets/art/empty/diary.png'),
  lab: require('../../assets/art/empty/lab.png'),
  meds: require('../../assets/art/empty/meds.png'),
  pharmacy: require('../../assets/art/empty/pharmacy.png'),
  records: require('../../assets/art/empty/records.png'),
  search: require('../../assets/art/empty/search.png'),
  symptoms: require('../../assets/art/empty/symptoms.png'),
  visits: require('../../assets/art/empty/visits.png'),
} satisfies Record<string,ImageSourcePropType>;

export const REFERRAL_ART={
  hero: require('../../assets/art/referral/hero.png'),
  share: require('../../assets/art/referral/share.png'),
} satisfies Record<string,ImageSourcePropType>;

export const COIN_ART:ImageSourcePropType=require('../../assets/art/coin.png');
