import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Camera,CheckCircle2,Gift,LoaderCircle,ShieldCheck,Trophy} from 'lucide-react';
import * as cloud from './cloud';
import type {Claim,Signal} from './cloud';
import {native,embedded} from './bridge';
import {formatDistance} from './engine';
const GiftScene=lazy(()=>import('./GiftScene'));
const labels:Record<string,string>={PENDING:'ადმინის შემოწმებას ელოდება',APPROVED:'დადასტურებულია',FULFILLED:'გაცემულია',REJECTED:'უარყოფილია'};
export default function CloudProfile(){
 const [profile,setProfile]=useState(cloud.currentSnapshot),[name,setName]=useState(profile.handle),[optIn,setOptIn]=useState(profile.leaderboardOptIn),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void cloud.api<cloud.Snapshot>('/bootstrap').then(setProfile).catch(e=>setStatus(e.message));},[]);
 async function save(){setBusy(true);try{setProfile(await cloud.saveSettings({handle:name,leaderboardOptIn:optIn}));setStatus('პარამეტრები შენახულია.');}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 return <section className="page-content"><div className="page-heading"><span className="eyebrow mint"><ShieldCheck size={14}/> MEDICARD ანგარიში</span><h1>შენი გზის ისტორია</h1><p>რეალური გასეირნება და აღმოჩენები შენს ანგარიშთანაა დაკავშირებული.</p></div><div className="cloud-settings"><label>საჯარო სახელი<input value={name} maxLength={30} onChange={e=>setName(e.target.value)}/></label><label><input type="checkbox" checked={optIn} onChange={e=>setOptIn(e.target.checked)}/> რეიტინგში მონაწილეობა საჯარო სახელით</label><button className="primary full" onClick={save} disabled={busy}>შენახვა</button>{status&&<p role="status" className="inline-note">{status}</p>}<p className="fine-print">რეიტინგში შენი ზუსტი მდებარეობა და სამედიცინო ინფორმაცია არ ჩანს. ანგარიშიდან გასვლისას პროგრესი ბაზაში რჩება.</p>{profile.claims.map(c=><article className="claim-card" key={c.id}><Gift size={20}/><strong>{c.reward.title}</strong><span>{labels[c.status]}</span><code>{c.code}</code></article>)}{!profile.claims.length&&<p className="quiet-note">პირველი რეალური აღმოჩენა ჯერ წინ გელოდება.</p>}{profile.history.length>0&&<><h3>შენახული გასეირნებები</h3>{profile.history.slice(0,10).map(h=><article key={h.id} className="claim-card"><strong>{formatDistance(h.meters)} · {Math.round(h.seconds/60)} წუთი</strong><small>{new Date(h.startedAt).toLocaleString('ka-GE')} · ≈ {Math.round(h.steps)} ნაბიჯი</small></article>)}</>}{!native&&!embedded&&<button className="text-button" onClick={cloud.logout}>ანგარიშიდან გასვლა</button>}</div></section>;
}
export function CloudLeaderboard(){
 const [period,setPeriod]=useState('week'),[rows,setRows]=useState<Array<{handle:string;newMeters:number;meters:number}>>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setError('');void cloud.api('/leaderboard?period='+period).then(data=>{if(alive)setRows(data.rows);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[period]);
 return <section className="page-content"><div className="page-heading"><span className="eyebrow mint">ნამდვილი ნაბიჯები</span><h1>ქალაქის მკვლევრები</h1><p>დასრულებული გასეირნებების დადასტურებული მანძილი — ნებისმიერი ქალაქიდან.</p></div><div className="filter-row">{[['week','7 დღე'],['season','90 დღე']].map(([id,title])=><button key={id} className={period===id?'active':''} onClick={()=>setPeriod(id)}>{title}</button>)}</div><div className="ranking-hero"><Trophy size={32}/><strong>ერთად უფრო შორს.</strong><span>ყოველი დადასტურებული გასეირნება ითვლება.</span></div>{loading?<p role="status">რეიტინგი იტვირთება…</p>:error?<p role="alert">{error}</p>:<div className="rank-table">{rows.map((r,i)=><div className="rank-row" key={i}><span className="rank-number">{i+1}</span><span className="rank-avatar">{r.handle[0]}</span><strong>{r.handle}</strong><span>{formatDistance(r.meters)}</span></div>)}{!rows.length&&<p className="quiet-note">ამ პერიოდში შედეგი ჯერ არ არის. მონაწილეობა პროფილიდან ჩართე.</p>}</div>}<p className="quiet-note">დემო არ მონაწილეობს. რეიტინგში შესვლა ნებაყოფლობითია; ზუსტი მარშრუტი საჯაროდ არ ჩანს.</p></section>;
}
export function CloudGift({gift}:{gift:Signal['gift']}){
 const [claim,setClaim]=useState<Claim|null>(null),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[error,setError]=useState('');const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),alive=useRef(true);
 useEffect(()=>()=>{alive.current=false;stream.current?.getTracks().forEach(track=>track.stop());},[]);
 useEffect(()=>{if(camera&&video.current){video.current.srcObject=stream.current;void video.current.play().catch(()=>{});}},[camera]);
 async function enableCamera(){try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;setCamera(true);}catch{setError('კამერა ვერ ჩაირთო. 3D ყუთი კამერის გარეშეც შეგიძლია გახსნა.');}}
 async function open(){if(!gift||busy)return;setBusy(true);setError('');try{setClaim(await cloud.claimGift(gift.id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="gift-flow"><span className="eyebrow mint">{claim?'აღმოჩენა შენახულია':'პულსმა აქ მოგიყვანა'}</span><div className={'gift-stage '+(camera?'camera-stage':'')}>{camera&&<video ref={video} autoPlay muted playsInline/>}<Suspense fallback={<LoaderCircle className="spin"/>}><GiftScene opened={!!claim} camera={camera}/></Suspense></div>{claim?<><CheckCircle2 className="mint"/><h3>{claim.reward.title}</h3><p>{labels[claim.status]}</p><div className="reward-confirm"><ShieldCheck/><code>{claim.code}</code></div><p className="fine-print">{claim.reward.kind==='PHYSICAL'?'ეს მიღების განაცხადია. ფიზიკური პრიზი შემოწმებისა და ადმინის მიერ დადასტურების შემდეგ გაიცემა.':'ციფრული ჯილდო შენს კოლექციაში შენახულია.'}</p></>:<><h3>{gift?.title||'საჩუქარი ახლოს აღარ ჩანს'}</h3><p>{gift?.description||'ახალი აღმოჩენისთვის გააგრძელე გასეირნება.'}</p><button className="primary full" onClick={open} disabled={busy||!gift}>{busy?<LoaderCircle className="spin"/>:<Gift/>} {busy?'მოწმდება…':'გახსენი საჩუქარი'}</button>{!camera&&<button className="text-button" onClick={enableCamera}><Camera size={18}/> კამერაში ნახვა</button>}<p className="fine-print">იყავი უსაფრთხო ადგილას და შეინარჩუნე GPS სიგნალი. კამერის ხედი 3D ეფექტია; ზედაპირის ამოცნობა არ გამოიყენება.</p></>}{error&&<p role="alert" className="inline-note">{error}</p>}</div>;
}
