import {useState} from 'react';
import {ArrowUpRight,Check,CheckCircle2,ChevronRight,Compass,Flag,Flower2,Footprints,Landmark,MapPin,Mountain,Search,Sparkles,Stamp,Trees,Waves,Waypoints} from 'lucide-react';
import {MISSIONS,CHAPTERS,missionProgress,missionPercent} from './missions';
import type {Mission,MissionBook,Chapter} from './missions';
import {distance,formatDistance} from './engine';
import type {Coordinate} from './engine';
const ICONS={trees:Trees,landmark:Landmark,waves:Waves,mountain:Mountain,bridge:Waypoints,flower:Flower2};
export function MissionArt({mission,done=false,large=false}:{mission:Mission;done?:boolean;large?:boolean}){const Icon=ICONS[mission.icon];return <div className={`mission-art ${mission.chapter} ${done?'earned':''} ${large?'large':''}`} aria-hidden="true"><span className="stamp-perforation"/><span className="stamp-orbit"/><Icon strokeWidth={1.35}/><small>{done?'აღმოჩენილია':'თბილისი'}</small>{done&&<i><Check size={12}/></i>}</div>;}
type Props={book:MissionBook;position:Coordinate;source:'demo'|'gps';onMission:(m:Mission)=>void;onHelp:()=>void;hasLocation:boolean};
export default function Passport({book,position,source,onMission,onHelp,hasLocation}:Props){
 const [chapter,setChapter]=useState<Chapter|'all'>('all'),[search,setSearch]=useState(''),[filter,setFilter]=useState<'all'|'near'|'done'>('all');
 const complete=MISSIONS.filter(m=>missionProgress(book,m).completedAt),selected=MISSIONS.find(m=>m.id===book.selected&&!missionProgress(book,m).completedAt),suggested=selected||[...MISSIONS].filter(m=>!missionProgress(book,m).completedAt).sort((a,b)=>distance(position,a.center)-distance(position,b.center))[0];
 let list=MISSIONS.filter(m=>(chapter==='all'||m.chapter===chapter)&&(!search||`${m.name} ${m.title}`.toLocaleLowerCase('ka').includes(search.toLocaleLowerCase('ka')))&&(filter!=='done'||missionProgress(book,m).completedAt));if(filter==='near')list=[...list].sort((a,b)=>distance(position,a.center)-distance(position,b.center));
 return <section className="page-content passport-page"><div className="passport-heading"><span className="eyebrow mint"><Stamp size={14}/>თბილისის პასპორტი</span><h1>ქალაქს ჯერ კიდევ<br/><span>ბევრი ამბავი აქვს.</span></h1><p>შენი ტემპი. ახალი ადგილები. მოგონებები, რომლებიც შენთან რჩება.</p></div>
  <div className="passport-cover"><div><span className="passport-edition">თბილისი / კოლექცია 01</span><strong>{complete.length}<span> / {MISSIONS.length}</span></strong><p>მოპოვებული შტამპი</p><div className="passport-ticks" aria-label={`${complete.length} მისია ${MISSIONS.length}-დან`}>{MISSIONS.map(m=><i key={m.id} className={missionProgress(book,m).completedAt?'done':''}/>)}</div><small>{source==='demo'?'დემოს პასპორტი':'შენი GPS პასპორტი'}</small></div><div className="passport-emblem"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="50"/><circle cx="60" cy="60" r="43"/><path d="M27 78h66M34 77V52l10-8 10 8v25m9 0V38h13v39m0-25h10v25M63 38l7-13 6 13M38 59h12m-12 8h12m17-18h5m-5 9h5m-5 9h5"/></svg><span>აღმოაჩინე<br/>თბილისი</span></div></div>
  <div className="chapter-strip" aria-label="მისიების თავები"><button onClick={()=>setChapter('all')} aria-pressed={chapter==='all'} className={chapter==='all'?'active':''}>ყველა ადგილი</button>{CHAPTERS.map(c=><button key={c.id} onClick={()=>setChapter(c.id)} aria-pressed={chapter===c.id} className={chapter===c.id?'active':''}>{c.name}</button>)}</div>
  {chapter==='all'&&suggested&&!search&&filter==='all'&&<button className="next-discovery" onClick={()=>onMission(suggested)}><span className="next-icon"><Compass size={23}/></span><span><small>{selected?'შენი არჩეული მისია':'შემდეგი პატარა აღმოჩენა'}</small><strong>{suggested.name}</strong></span><ArrowUpRight size={20}/></button>}
  {chapter!=='all'&&<div className="chapter-heading"><span>{CHAPTERS.find(c=>c.id===chapter)?.symbol}</span><div><h2>{CHAPTERS.find(c=>c.id===chapter)?.name}</h2><p>{CHAPTERS.find(c=>c.id===chapter)?.subtitle}</p></div><small>{complete.filter(m=>m.chapter===chapter).length}/{MISSIONS.filter(m=>m.chapter===chapter).length}</small></div>}
  <label className="mission-search"><Search size={18}/><input aria-label="მოძებნე ადგილი" placeholder="რომელ ადგილს აღმოაჩენ?" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="ძებნის გასუფთავება" onClick={()=>setSearch('')}>×</button>}</label>
  <div className="passport-filters"><div>{[{id:'all' as const,label:'ყველა'},{id:'near' as const,label:'ახლომახლო'},{id:'done' as const,label:'ჩემი შტამპები'}].map(f=><button key={f.id} className={filter===f.id?'active':''} aria-pressed={filter===f.id} onClick={()=>setFilter(f.id)}>{f.label}</button>)}</div><span>{list.length} ადგილი</span></div>
  {filter==='near'&&<p className="fine-print">{source==='demo'?'დაშორება დემოს პინიდან ითვლება.':hasLocation?'დაშორება პირდაპირი ხაზითაა, არა სავალი მარშრუტი.':'ზუსტი დაშორებისთვის დაიწყე GPS გასეირნება. სია საწყისი პინიდანაა დალაგებული.'}</p>}
  <div className="mission-grid">{list.map(m=>{const p=missionProgress(book,m),percent=missionPercent(book,m);return <button key={m.id} className={`mission-card ${p.completedAt?'complete':''} ${book.selected===m.id?'selected':''}`} onClick={()=>onMission(m)}><MissionArt mission={m} done={!!p.completedAt}/><div className="mission-card-copy"><span className="mission-card-kicker">{p.completedAt?'შენი პასპორტიდან':book.selected===m.id?'არჩეული მისია':CHAPTERS.find(c=>c.id===m.chapter)?.name}</span><h3>{m.name}</h3><p><Footprints size={13}/>{formatDistance(m.meters)}<span>·</span>{filter==='near'&&(hasLocation||source==='demo')?formatDistance(distance(position,m.center))+' დაშორებით':m.title}</p><div className="mission-card-progress"><span><i style={{width:percent+'%'}}/></span><small>{p.completedAt?<CheckCircle2 size={14}/>:percent+'%'}</small></div></div><ChevronRight className="mission-card-arrow" size={16}/></button>;})}</div>
  {!list.length&&<div className="mission-empty"><Search size={30}/><h3>{filter==='done'?'პირველი შტამპი წინ გელოდება':'ადგილი ვერ მოიძებნა'}</h3><p>{filter==='done'?'აირჩიე მისია და დაიწყე შენი გასეირნება.':'შეცვალე ძებნა ან აირჩიე სხვა თავი.'}</p><button className="text-button" onClick={()=>{setFilter('all');setChapter('all');setSearch('');}}>ყველა ადგილის ნახვა</button></div>}
  <button className="passport-help" onClick={onHelp}><Sparkles size={18}/><span>როგორ იქცევა გასეირნება შტამპად?</span><ArrowUpRight size={17}/></button><p className="fine-print">მისიის შტამპი და ტერიტორიის გაფერადება სხვადასხვა მიღწევაა. კოლექციის პროცენტი თბილისის ფართობის პროცენტი არ არის.</p>
 </section>;
}
export function MissionDetails({mission:m,book,source,onChoose,onPreview,onStop,onDemo}:{mission:Mission;book:MissionBook;source:'demo'|'gps';onChoose:()=>void;onPreview:()=>void;onStop:()=>void;onDemo:()=>void}){
 const p=missionProgress(book,m),active=book.selected===m.id;
 return <div className="mission-details"><div className="mission-detail-art"><MissionArt mission={m} done={!!p.completedAt} large/><span>{CHAPTERS.find(c=>c.id===m.chapter)?.name}</span></div><h3>{m.title}</h3><p>{m.story}</p><div className="mission-objectives"><div><Footprints size={18}/><span>ზონაში გასავლელი<strong>{formatDistance(p.meters)} / {formatDistance(m.meters)}</strong></span>{p.meters>=m.meters&&<CheckCircle2 size={17}/>}</div><div><Compass size={18}/><span>ჩათვლილი მოძრაობის დრო<strong>{Math.floor(p.seconds)} / {m.seconds} წამი</strong></span>{p.seconds>=m.seconds&&<CheckCircle2 size={17}/>}</div><div><MapPin size={18}/><span>მისიის რადიუსი<strong>{m.radius} მეტრი · გარე სივრცე</strong></span></div></div><p className="mission-rule">ორივე მიზანი შეასრულე არჩეული მისიის ზონაში. შეგიძლია რამდენიმე გასეირნებად შეაგროვო. პროგრესი შენახულია.</p><div className="mission-tip"><Flag size={17}/><p>{m.tip}</p></div>
  {p.completedAt?<div className="mission-earned"><Stamp size={20}/><span>ეს ამბავი უკვე შენია<strong>შტამპი მიღებულია · {new Date(p.completedAt).toLocaleDateString('ka-GE')}</strong></span></div>:<button className="primary full" onClick={onChoose}><Flag size={17}/>{active?'მისიაზე დაბრუნება':'აირჩიე ეს მისია'}</button>}
  <button className="text-button" onClick={onPreview}><MapPin size={17}/>ზონის ნახვა რუკაზე</button>{active&&<button className="text-button muted" onClick={onStop}>არჩევის მოხსნა · პროგრესი დარჩება</button>}
  {source==='demo'&&<div className="mission-demo-note"><small>დემოს მოძრაობა ვაკის პარკის ბილიკებზე მუშაობს. სხვა ადგილების მისიები რეალური GPS გასეირნებისთვისაა.</small>{m.id==='vake'&&<button onClick={onDemo}><Footprints size={15}/>ვაკის მისიის დემო</button>}</div>}
  <p className="fine-print">წრე საორიენტაციო სათამაშო ზონაა და არა ოფიციალური საზღვარი. ცენტრში ზუსტად მისვლა საჭირო არ არის. შტამპი ციფრული მიღწევაა და ფიზიკურ პრიზს არ ნიშნავს. <a href={m.source} target="_blank" rel="noreferrer">ადგილის წყარო ↗</a></p>
 </div>;
}
