import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {Activity,ArrowRight,Award,Camera,CheckCircle2,Gift,LoaderCircle,Sparkles,X} from 'lucide-react';
const GiftScene=lazy(()=>import('./GiftScene'));
export function Modal({children,title,onClose,wide=false}:{children:React.ReactNode;title:string;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} aria-label={title} className={`modal ${wide?'wide':''}`} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="დახურვა" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;}
function PulseLine(){return <svg className="pulse-line" viewBox="0 0 230 40" aria-hidden="true"><path d="M0 20h55l6-5 7 10 9-9 8 3 9-15 10 33 10-22 7 5h109"/></svg>;}
export function Brand(){return <div className="brand"><span className="brand-mark"><Activity size={24}/></span><span><strong>პულსი<span className="brand-dot">.</span></strong><small>BY MEDICARD AI</small></span></div>;}
export function ProgressRing({percent,size=64}:{percent:number;size?:number}){const r=26,c=2*Math.PI*r;return <div className="progress-ring" style={{width:size,height:size}}><svg viewBox="0 0 64 64"><circle className="ring-track" cx="32" cy="32" r={r}/><circle className="ring-fill" cx="32" cy="32" r={r} strokeDasharray={c} strokeDashoffset={c*(1-percent/100)}/></svg><strong>{percent}<small>%</small></strong></div>;}
export function GiftFlow({claimed,onClaim}:{claimed:boolean;onClaim:()=>void}){
 const [opened,setOpened]=useState(claimed),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[error,setError]=useState('');const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),alive=useRef(true),timer=useRef<number|undefined>(undefined);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;stream.current?.getTracks().forEach(t=>t.stop());clearTimeout(timer.current);};},[]);
 async function enableCamera(){setError('');if(!navigator.mediaDevices?.getUserMedia){setError('კამერა ამ ბრაუზერში მიუწვდომელია. ყუთი შეგიძლია აქვე გახსნა.');return;}try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(!alive.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;setCamera(true);}catch{setError('კამერა ვერ ჩაირთო. შენი საცდელი საჩუქარი ხელმისაწვდომია კამერის გარეშეც.');}}
 useEffect(()=>{if(camera&&video.current){video.current.srcObject=stream.current;void video.current.play().catch(()=>setError('კამერის ჩვენება ვერ მოხერხდა. გამოიყენე 3D რეჟიმი.'));}},[camera]);
 function open(){if(busy||opened)return;setBusy(true);setOpened(true);timer.current=window.setTimeout(()=>{onClaim();setBusy(false);},1100);}
 return <div className="gift-flow"><span className="eyebrow mint"><Sparkles size={14}/>{claimed?'შენი აღმოჩენა':'პულსმა სწორ ადგილას მოგიყვანა'}</span><div className={`gift-stage ${camera?'camera-stage':''}`}>{camera&&<video ref={video} autoPlay muted playsInline/>}<Suspense fallback={<div className="scene-loading"><LoaderCircle className="spin"/></div>}><GiftScene opened={opened} camera={camera}/></Suspense><span className="demo-pill">{camera?'კამერის დემო · ზედაპირზე მიბმის გარეშე':'საცდელი 3D საჩუქარი'}</span></div>{claimed?<><h3>პირველი აღმოჩენა!</h3><p>შენს კოლექციას ვაკის მკვლევრის ნიშანი დაემატა.</p><div className="reward-confirm"><Award/><div><strong>ვაკის მკვლევარი</strong><small>ციფრული ნიშანი · საცდელი ჯილდო</small></div><CheckCircle2/></div></>:<><h3>პატარა აღმოჩენა.<br/>დიდი თავგადასავლის დასაწყისი.</h3><p>გახსენი ყუთი და ნახე შენი პირველი საცდელი ჯილდო.</p><button className="primary full" onClick={open} disabled={busy}>{busy?<LoaderCircle className="spin" size={19}/>:<Gift size={19}/>} {busy?'იხსნება…':'გახსენი საჩუქარი'}</button>{!camera&&<button className="text-button camera-button" onClick={enableCamera}><Camera size={18}/>კამერაში ნახვა</button>}</>}{error&&<p role="status" className="inline-note">{error}</p>}<p className="fine-print">ეს დემოა. ფიზიკური პრიზი არ გაიცემა.</p></div>;
}
