const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const root=path.resolve(__dirname,'../src');
function loader(mocks={}){const cache=new Map();function load(file){file=path.resolve(file);if(!path.extname(file))file+='.ts';if(cache.has(file))return cache.get(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));const module={exports:{}};cache.set(file,module.exports);const requireLocal=id=>{if(id in mocks)return mocks[id];if(id.startsWith('@/'))return load(path.join(root,id.slice(2)));if(id.startsWith('.'))return load(path.resolve(path.dirname(file),id));return require(id);};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const wrap=vm.runInThisContext('(function(require,module,exports,setInterval,clearInterval,__DEV__){'+code+'\n})',{filename:file});wrap(requireLocal,module,module.exports,(fn,ms)=>setInterval(fn,ms).unref(),clearInterval,true);return module.exports;}return load;}
const load=loader(),{PulseSessionClient}=load(root+'/lib/medipulsi/sessionClient.ts'),{createJourney,acceptFix}=load(root+'/lib/medipulsi/core/journey.ts'),{pauseJourney,resetSession}=load(root+'/lib/medipulsi/core/session.ts'),{emptyBook}=load(root+'/lib/medipulsi/core/missions.ts');
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function harness(){let server={userId:'one',state:{journey:createJourney('gps'),book:emptyBook()},settings:{},handle:'tester',leaderboardOptIn:false,session:null,history:[],claims:[],missions:[],config:{enabled:true,giftsEnabled:true,leaderboardEnabled:true,message:''}},stored=null,offline=false,conflict=false,id=0,requests=[],archived=[],seen=new Set();
 const adapter={id:()=>`test-${++id}`,read:async()=>stored,write:async value=>{stored=value;},archive:async value=>archived.push(value),request:async(url,method='GET',body)=>{
  requests.push({url,method,body:structuredClone(body)});if(offline)throw new Error('offline');
  if(url==='/bootstrap')return structuredClone(server);
  if(url==='/sessions'){server.session={id:body.id,seq:0,phase:'ACTIVE'};server.state.journey=resetSession(server.state.journey);return structuredClone(server);}
  if(url.endsWith('/batches')){if(conflict)throw Object.assign(new Error('sequence conflict'),{status:409});if(seen.has(body.id))return {seq:server.session.seq};assert.equal(body.seq,server.session.seq+1);for(const fix of body.fixes)if(!fix.mocked)server.state.journey=acceptFix(server.state.journey,fix,.72,fix.timestamp);seen.add(body.id);server.session.seq=body.seq;return {seq:body.seq};}
  if(url.endsWith('/finish')){server.history.push({meters:server.state.journey.meters});server.state.journey=resetSession(server.state.journey);server.session=null;return structuredClone(server);}
  if(url.endsWith('/pause')||url.endsWith('/resume')){if(!server.session)throw Object.assign(new Error('finished'),{status:409});server.state.journey=pauseJourney(server.state.journey);server.session.phase=url.endsWith('/pause')?'PAUSED':'ACTIVE';return structuredClone(server);}
  if(url==='/nearby')return {signal:false};throw new Error('unexpected '+url);
 }};
 return {adapter,client:new PulseSessionClient(adapter),requests,archived,get server(){return server;},get stored(){return stored;},set offline(value){offline=value;},set conflict(value){conflict=value;}};
}
function fixes(client,start=[-73.97,40.77],count=5,now=Date.now()-20000){for(let i=0;i<count;i++)client.ingest({position:[start[0]+i*.00006,start[1]],accuracy:5,timestamp:now+i*4000,speed:1.3});}
test('native outbox retains global movement offline and retries the same sequence',async()=>{const h=harness();await h.client.begin();h.offline=true;fixes(h.client);await h.client.flush().catch(()=>{});assert.ok(h.client.getSnapshot().journey.meters>15);assert.ok(h.client.getSnapshot().pending>0);const queued=JSON.parse(h.stored).queue[0];h.offline=false;await h.client.flush();assert.equal(h.server.session.seq,1);assert.ok(h.server.state.journey.trail.length);assert.equal(h.requests.filter(r=>r.url.endsWith('/batches')).at(-1).body.id,queued.body.id);h.client.dispose();});
test('pause/resume never joins a journey across continents; finish keeps both traces',async()=>{const h=harness();await h.client.begin();fixes(h.client);await h.client.flush();const before=h.client.getSnapshot().journey.meters;h.client.stop();await h.client.flush();await h.client.begin();const start=Date.now();h.client.ingest({position:[151.2,-33.86],accuracy:5,timestamp:start,speed:0});assert.equal(h.client.getSnapshot().journey.meters,before);fixes(h.client,[151.2,-33.86],5,start+4000);await h.client.flush();h.client.stop(true);await h.client.flush();assert.equal(h.server.session,null);assert.ok(h.server.state.journey.trail.length>=2);assert.equal(h.client.getSnapshot().journey.meters,0);h.client.dispose();});
test('cold recovery replays cached fixes before pausing the owned server session',async()=>{const h=harness();await h.client.begin();h.offline=true;fixes(h.client);await h.client.flush().catch(()=>{});h.client.dispose();h.offline=false;const recovered=new PulseSessionClient(h.adapter);await recovered.init();assert.equal(h.server.session.phase,'PAUSED');assert.ok(recovered.getSnapshot().journey.meters>15);assert.equal(recovered.getSnapshot().journey.lastFix,null);assert.equal(recovered.getSnapshot().running,false);recovered.dispose();});
test('concurrent-device sequence conflicts are archived, not silently recredited',async()=>{const h=harness();await h.client.begin();h.conflict=true;fixes(h.client);await h.client.flush();assert.equal(h.archived.length,1);assert.equal(h.client.getSnapshot().running,false);assert.equal(h.client.getSnapshot().conflict,true);assert.equal(h.server.state.journey.meters,0);h.client.dispose();});
test('mock GPS never gives the native player distance',async()=>{const h=harness();await h.client.begin();h.client.ingest({position:[139.7,35.6],accuracy:5,timestamp:Date.now(),speed:1,mocked:true});assert.equal(h.client.getSnapshot().journey.meters,0);h.client.stop(true);await h.client.flush();h.client.dispose();});
test('completed cached session recovers instead of an infinite 409 retry',async()=>{const h=harness();await h.client.begin();h.client.dispose();h.server.session=null;const recovered=new PulseSessionClient(h.adapter);await recovered.init();assert.equal(recovered.getSnapshot().loading,false);await recovered.begin();assert.ok(recovered.getSnapshot().running);recovered.dispose();});
test('disposed account cannot apply a late response to the current view',async()=>{const pending=defer(),h=harness(),client=new PulseSessionClient({...h.adapter,request:()=>pending.promise});const init=client.init();await Promise.resolve();client.dispose();pending.resolve(h.server);await init;assert.equal(client.getSnapshot().snapshot,null);});

function storeHarness(snapshotLoader=async()=>null){const h=harness();let callback,headingCallback,removed=0,requested=0,watchCalls=0,saved=null,subscriptionGate=null;const app={currentState:'active',addEventListener:()=>({remove(){}})};
 const location={Accuracy:{High:4,BestForNavigation:6},getForegroundPermissionsAsync:async()=>({granted:true}),getCurrentPositionAsync:async()=>({coords:{latitude:40.77,longitude:-73.97,accuracy:5}}),watchPositionAsync:async(_opts,fn)=>{watchCalls++;callback=fn;if(subscriptionGate)await subscriptionGate.promise;return {remove(){removed++;}};},watchHeadingAsync:async fn=>{headingCallback=fn;return {remove(){}};}};
 const geo=load(root+'/lib/run/geo.ts'),modules={react:{useSyncExternalStore:()=>{}},'react-native':{AppState:app},'expo-location':location,'@/lib/medipulsi/client':{getPulseClient:()=>h.client,resetPulseClient:()=>h.client.dispose()},'@/lib/run/activePersist':{clearActiveRun:async()=>{},saveActiveRun:async()=>{},loadActiveRun:snapshotLoader},'@/lib/run/history':{downsamplePath:p=>p,saveRunSummary:async s=>{saved=s;}},'@/lib/run/mapbox':{generateTargetPin:async()=>{throw new Error('Free walk must not request a city-specific route');}},'@/lib/userLocation':{requestLocationPermission:async()=>{requested++;return 'granted';}}};
 const store=loader(modules)(root+'/lib/run/store.ts');
 return {...h,store,app,location,get removed(){return removed;},get requested(){return requested;},get watchCalls(){return watchCalls;},get saved(){return saved;},set gate(value){subscriptionGate=value;},fix(lng,lat,at){callback({coords:{longitude:lng,latitude:lat,accuracy:5,speed:1,heading:90},timestamp:at});},heading(deg){headingCallback({trueHeading:deg,magHeading:deg});}};
}
test('MEDI RUN shares one GPS watcher, server distance, compass, and a single finish',async()=>{const h=storeHarness();await h.store.prepareExploration();assert.equal(h.requested,0);assert.equal(h.store.getRunState().pin,null);await Promise.all([h.store.startRun(),h.store.startRun()]);assert.equal(h.watchCalls,1);const now=Date.now()-10000;h.fix(-73.97,40.77,now);h.heading(210);h.fix(-73.96994,40.77,now+4000);assert.equal(h.store.getRunState().headingDeg,210);assert.equal(h.store.getRunState().distanceM,h.client.getSnapshot().journey.meters);h.store.pauseRun();assert.equal(h.removed,1);const paused=h.store.getRunState().distanceM;h.fix(151.2,-33.86,Date.now());assert.equal(h.store.getRunState().distanceM,paused);const summary=await h.store.finishRun();assert.ok(summary.segments.length);assert.equal(summary.completedTarget,false);await h.client.flush();h.store.resetRunMemory();});
test('GPS subscription completing after pause is immediately removed',async()=>{const h=storeHarness(),gate=defer();await h.store.prepareExploration();h.gate=gate;const start=h.store.startRun();while(h.watchCalls===0)await new Promise(r=>setTimeout(r,1));h.store.pauseRun();gate.resolve();await start;assert.equal(h.removed,1);assert.equal(h.store.getRunState().phase,'paused');h.store.resetRunMemory();});
test('map script parses, consumes persistent disconnected paint and contains no app authentication',()=>{const {buildRunMapHtml}=load(root+'/lib/run/mapHtml.ts');const html=buildRunMapHtml({token:'pk.test',center:{lat:40,lng:-73},dark:true});for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))assert.doesNotThrow(()=>new vm.Script(match[1]));assert.ok(html.includes("case 'paint'"));assert.ok(html.includes('AttributionControl'));assert.ok(!html.includes('Authorization'));assert.ok(!html.includes('lookaheadBearing'));});

const persisted={phase:'running',mode:'explore',target:{kind:'km',value:0},origin:{lat:40,lng:-73},current:{lat:40,lng:-73},path:[],movingAccumMs:10000,startedAt:Date.now()-12000,reachedPin:false,completedTarget:false,distanceM:12};
test('cold run restore stays paused and requests no OS permission or GPS watcher',async()=>{const h=storeHarness(async()=>persisted);assert.equal(await h.store.hydrateActiveRun(),true);assert.equal(h.store.getRunState().phase,'paused');assert.equal(h.watchCalls,0);assert.equal(h.requested,0);h.store.resetRunMemory();});
test('account reset rejects a late active-session load belonging to the previous account',async()=>{const pending=defer(),h=storeHarness(()=>pending.promise);const restore=h.store.hydrateActiveRun();h.store.resetRunMemory();pending.resolve(persisted);assert.equal(await restore,false);assert.equal(h.store.getRunState().phase,'idle');});
