'use strict';
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
const STORAGE='medicard.admin.poster-studio.v2.'+window.STUDIO_ACCOUNT;
let designs=clone(window.POSTER_DEFAULTS), current=designs[0].id, selected='headline', comparing=false, history=[], dragging=null, renderVersion=0, dirtyTimer;
try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved&&saved.version===2&&Array.isArray(saved.designs)) designs=validate(saved.designs);}catch{}
const canvas=$('poster'),ctx=canvas.getContext('2d'),images=new Map(),backgrounds=new Map(),boxes=[];
function validate(items){return window.POSTER_DEFAULTS.map(base=>{const saved=items.find(x=>x.id===base.id);if(!saved)return clone(base);const layers=(saved.layers||[]).slice(0,20).filter(l=>typeof l.text==='string').map(l=>({key:String(l.key).slice(0,60),name:String(l.name||'ტექსტი').slice(0,80),text:l.text.slice(0,1500),x:Math.max(0,Math.min(1080,Number(l.x)||0)),y:Math.max(0,Math.min(base.height||1350,Number(l.y)||0)),size:Math.max(10,Math.min(180,Number(l.size)||30)),font:l.font==='Davit'?'Davit':'Fira',weight:l.weight===600?600:400,color:/^#[0-9a-f]{6}$/i.test(l.color)?l.color:'#ffffff',lineHeight:Math.max(.9,Math.min(1.8,Number(l.lineHeight)||1.2))}));return {...clone(base),layers};});}
function design(){return designs.find(d=>d.id===current)}
function layer(){return design().layers.find(l=>l.key===selected)||design().layers[0]}
function status(t){$('status').textContent=t}
function stash(){try{localStorage.setItem(STORAGE,JSON.stringify({version:2,designs}));}catch{status('ბრაუზერში შენახვა ვერ მოხერხდა — შეინახე პროექტის ფაილი.')}}
function remember(){history.push(JSON.stringify(designs));if(history.length>50)history.shift()}
function getImage(src){if(images.has(src))return images.get(src);const promise=new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('სურათი ვერ ჩაიტვირთა: '+src));img.src=window.EMBEDDED_ASSETS?.[src]||src;});images.set(src,promise);return promise;}
async function background(d){if(backgrounds.has(d.id))return backgrounds.get(d.id);const pending=(async()=>{const [original,clean]=await Promise.all([getImage('assets/originals/'+d.id+'.png'),getImage('assets/clean/'+d.id+'.png')]);const result=document.createElement('canvas');result.width=1080;result.height=d.height||1350;const c=result.getContext('2d',{willReadFrequently:true});c.drawImage(original,0,0,1080,result.height);const under=c.getImageData(0,0,1080,result.height);const cleanCanvas=document.createElement('canvas');cleanCanvas.width=1080;cleanCanvas.height=result.height;const cc=cleanCanvas.getContext('2d',{willReadFrequently:true});cc.drawImage(clean,0,0,1080,result.height);const above=cc.getImageData(0,0,1080,result.height);for(const [rx,ry,rw,rh] of d.masks){const x0=Math.max(0,Math.floor(rx)),y0=Math.max(0,Math.floor(ry)),x1=Math.min(1080,Math.ceil(rx+rw)),y1=Math.min(result.height,Math.ceil(ry+rh));for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const fade=Math.min(1,(x-x0)/8,(x1-1-x)/8,(y-y0)/8,(y1-1-y)/8);const i=(y*1080+x)*4;for(let k=0;k<3;k++)under.data[i+k]=Math.round(under.data[i+k]*(1-fade)+above.data[i+k]*fade);}}c.putImageData(under,0,0);return result;})();backgrounds.set(d.id,pending);try{return await pending}catch(e){backgrounds.delete(d.id);throw e}}
function fontFor(l,size=l.size){return (l.font==='Davit'?'400':l.weight)+' '+size+'px '+l.font}
function layoutText(c,l,d){let size=l.size;const lines=l.text.split('\n');const maxWidth=1080-l.x-55;c.font=fontFor(l,size);let width=Math.max(0,...lines.map(s=>c.measureText(s).width));if(width>maxWidth){size*=maxWidth/width;c.font=fontFor(l,size)}if(l.key==='headline'){const sub=d.layers.find(x=>x.key==='sub');const room=sub?sub.y-l.y-18:999;size=Math.min(size,room/(lines.length*l.lineHeight));}return {size:Math.max(10,size),lines}}
function paintText(c,d,selection){boxes.length=0;for(const l of d.layers){if(!l.text)continue;const {size,lines}=layoutText(c,l,d);c.font=fontFor(l,size);c.textBaseline='top';let max=0;if(l.key==='cta'){const w=Math.max(...lines.map(s=>c.measureText(s).width));c.fillStyle='#073b38';c.beginPath();c.roundRect(l.x-25,l.y-14,w+50,size*lines.length*l.lineHeight+24,28);c.fill();}c.fillStyle=l.color;if(l.key==='disclaimer'){c.shadowColor=d.light?'transparent':'#000';c.shadowBlur=5;}lines.forEach((line,i)=>{c.fillText(line,l.x,l.y+i*size*l.lineHeight);max=Math.max(max,c.measureText(line).width)});c.shadowBlur=0;const box={key:l.key,x:l.x,y:l.y,w:max,h:size*l.lineHeight*lines.length};if(d.id===current)boxes.push(box);if(selection&&l.key===selected){c.save();c.strokeStyle='#50daca';c.setLineDash([7,5]);c.lineWidth=2;c.strokeRect(box.x-8,box.y-8,box.w+16,box.h+16);c.restore();}}}
async function draw(target=canvas,d=design(),selection=true){target.width=1080;target.height=d.height||1350;if(target===canvas)target.style.aspectRatio='1080 / '+target.height;const context=target.getContext('2d');context.clearRect(0,0,target.width,target.height);if(comparing&&target===canvas){const img=await getImage('assets/originals/'+d.id+'.png');context.drawImage(img,0,0,1080,target.height);return;}context.drawImage(await background(d),0,0);paintText(context,d,selection)}
async function refresh(){const version=++renderVersion;try{const bg=await background(design());if(version!==renderVersion)return;await draw();status('ცვლილებები ინახება ავტომატურად.')}catch(e){if(version===renderVersion)status(e.message)}}
function list(){const q=$('search').value.trim().toLowerCase();$('designList').replaceChildren();for(const d of designs){if(!(d.label+' '+d.headline).toLowerCase().includes(q))continue;const button=document.createElement('button');button.className='design-button'+(d.id===current?' active':'');button.setAttribute('aria-pressed',d.id===current);const im=document.createElement('img');im.alt='';im.src=window.EMBEDDED_ASSETS?.['posters/'+d.id+'.png']||'posters/'+d.id+'.png';im.onerror=()=>{im.onerror=null;im.src=window.EMBEDDED_ASSETS?.['assets/originals/'+d.id+'.png']||'assets/originals/'+d.id+'.png'};const span=document.createElement('span');span.textContent=d.label;button.append(im,span);button.onclick=()=>switchDesign(d.id);$('designList').append(button)}$('count').textContent=designs.length;}
function inspector(){const d=design();$('designTitle').textContent=d.label;$('dimensions').textContent='1080 × '+(d.height||1350)+(d.height?' · Story':' · Feed');$('y').max=d.height||1350;$('layer').replaceChildren();for(const l of d.layers){const option=new Option(l.name,l.key);$('layer').append(option)}if(!d.layers.some(l=>l.key===selected))selected=d.layers[0]?.key;$('layer').value=selected||'';const l=layer();for(const field of ['text','font','size','color','x','y','lineHeight','weight']){$(field).disabled=!l;if(l)$(field).value=l[field]}}
async function switchDesign(id){if(!designs.some(d=>d.id===id))return;current=id;comparing=false;$('compare').textContent='საწყისი დიზაინი';list();inspector();await refresh()}
$('search').addEventListener('input',list);$('layer').onchange=()=>{selected=$('layer').value;inspector();refresh()};
for(const field of ['text','font','size','color','x','y','lineHeight','weight']){$(field).addEventListener('focus',remember);$(field).addEventListener('input',()=>{const l=layer();if(!l)return;l[field]=['size','x','y','lineHeight','weight'].includes(field)?Number($(field).value):$(field).value;comparing=false;stash();refresh()})}
$('compare').onclick=()=>{comparing=!comparing;$('compare').textContent=comparing?'რედაქტორში დაბრუნება':'საწყისი დიზაინი';refresh()};
$('undo').onclick=()=>{if(!history.length)return;designs=JSON.parse(history.pop());stash();list();inspector();refresh()};
$('reset').onclick=()=>{remember();designs[designs.findIndex(d=>d.id===current)]=clone(window.POSTER_DEFAULTS.find(d=>d.id===current));stash();inspector();refresh()};
$('addLayer').onclick=()=>{remember();const l={key:'custom-'+Date.now(),name:'ახალი წარწერა',text:'ახალი წარწერა',x:65,y:600,size:36,font:'Fira',weight:400,color:design().light?'#32132b':'#ffffff',lineHeight:1.2};design().layers.push(l);selected=l.key;stash();inspector();refresh()};
$('removeLayer').onclick=()=>{remember();design().layers=design().layers.filter(l=>l.key!==selected);selected=design().layers[0]?.key;stash();inspector();refresh()};
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*1080/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.onpointerdown=e=>{if(comparing)return;const p=point(e);const hit=[...boxes].reverse().find(b=>p.x>=b.x-12&&p.x<=b.x+b.w+12&&p.y>=b.y-12&&p.y<=b.y+b.h+12);if(!hit)return;selected=hit.key;const l=layer();remember();dragging={dx:p.x-l.x,dy:p.y-l.y};canvas.setPointerCapture(e.pointerId);inspector();refresh()};
canvas.onpointermove=e=>{if(!dragging)return;const p=point(e),l=layer();l.x=Math.round(Math.max(0,Math.min(1000,p.x-dragging.dx)));l.y=Math.round(Math.max(0,Math.min(canvas.height-50,p.y-dragging.dy)));$('x').value=l.x;$('y').value=l.y;refresh()};canvas.onpointerup=()=>{dragging=null;stash()};canvas.onpointercancel=()=>{dragging=null;stash()};
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000)}
async function exportBlob(d){await fontsReady;const out=document.createElement('canvas');out.width=1080;out.height=d.height||1350;await draw(out,d,false);return new Promise(resolve=>out.toBlob(resolve,'image/png'))}
$('export').onclick=async()=>{const b=$('export');b.disabled=true;try{download(await exportBlob(design()),design().id+'.png');status('PNG მზადაა — 1080 × '+(design().height||1350)+'.')}catch(e){status(e.message)}finally{b.disabled=false}};
$('exportAll').onclick=async()=>{const b=$('exportAll');b.disabled=true;try{const zip=new JSZip();for(let i=0;i<designs.length;i++){status('მზადდება '+(i+1)+' / '+designs.length);zip.file(designs[i].id+'.png',await exportBlob(designs[i]))}zip.file('project.json',JSON.stringify({version:2,designs},null,2));download(await zip.generateAsync({type:'blob',compression:'STORE'}),'MEDICARD-posters.zip');status('ყველა პოსტერი მზადაა.')}catch(e){status(e.message)}finally{b.disabled=false;refresh()}};
$('saveProject').onclick=()=>download(new Blob([JSON.stringify({version:2,designs},null,2)],{type:'application/json'}),'MEDICARD-project.json');
$('openProject').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const incoming=JSON.parse(await file.text());if(incoming.version!==2||!Array.isArray(incoming.designs))throw new Error('ეს არ არის MEDICARD Studio-ს პროექტის ფაილი.');remember();designs=validate(incoming.designs);stash();inspector();list();refresh()}catch(error){status(error.message)}finally{e.target.value=''}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='z'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('undo').click()}});
const fontsReady=Promise.all([document.fonts.load('400 80px Davit','ყველაფერი შენი ჯანმრთელობისთვის'),document.fonts.load('400 25px Fira','ქართული'),document.fonts.load('600 25px Fira','ქართული')]);
window.STUDIO={exportBlob,get designs(){return designs},switchDesign,background,async renderDataURL(id){const d=designs.find(d=>d.id===id);await fontsReady;const c=document.createElement('canvas');c.width=1080;c.height=d.height||1350;await draw(c,d,false);return c.toDataURL('image/png')},async backgroundDataURL(id){return(await background(designs.find(d=>d.id===id))).toDataURL('image/png')}};
list();inspector();fontsReady.then(refresh).catch(()=>status('ფონტი ვერ ჩაიტვირთა — გახსენი სტუდია ადგილობრივი სერვერიდან.'));
