import {Router} from 'express';
import {z} from 'zod';
import rateLimit from 'express-rate-limit';
import {requireAuth} from '../middleware/auth.js';
import {asyncHandler} from '../middleware/error.js';
import {RATE_LIMIT_VALIDATE} from '../lib/rateLimitKey.js';
import {env} from '../config/env.js';
import * as game from '../lib/medipulsi/service.js';
import {id,batchSchema,settingsSchema,fail} from '../lib/medipulsi/schema.js';
export const medipulsiRouter=Router();
medipulsiRouter.use(requireAuth,(req,res,next)=>{res.set('Cache-Control','no-store');if(req.user.status!=='ACTIVE')return res.status(403).json({error:'საჭიროა აქტიური ანგარიში.'});next();});
const write=rateLimit({windowMs:60000,limit:180,standardHeaders:true,legacyHeaders:false,validate:RATE_LIMIT_VALIDATE});
medipulsiRouter.get('/bootstrap',asyncHandler(async(req,res)=>res.json({...await game.bootstrap(req.user.id),mapboxToken:env.MAPBOX_PUBLIC_TOKEN||process.env.MAPBOX_PUBLIC_TOKEN||''})));
medipulsiRouter.patch('/settings',write,asyncHandler(async(req,res)=>res.json(await game.settings(req.user.id,settingsSchema.parse(req.body)))));
medipulsiRouter.put('/mission',write,asyncHandler(async(req,res)=>res.json(await game.selectMission(req.user.id,z.object({id:id.nullable()}).strict().parse(req.body).id))));
medipulsiRouter.post('/sessions',write,asyncHandler(async(req,res)=>res.json(await game.start(req.user.id,z.object({id:z.uuid()}).strict().parse(req.body).id))));
medipulsiRouter.post('/sessions/:id/batches',write,asyncHandler(async(req,res)=>res.json(await game.batch(req.user.id,id.parse(req.params.id),batchSchema.parse(req.body)))));
medipulsiRouter.post('/sessions/:id/:action',write,asyncHandler(async(req,res)=>res.json(await game.control(req.user.id,id.parse(req.params.id),z.enum(['pause','resume','finish']).parse(req.params.action)))));
medipulsiRouter.get('/nearby',asyncHandler(async(req,res)=>res.json(await game.nearby(req.user.id))));
medipulsiRouter.post('/gifts/:id/claim',write,asyncHandler(async(req,res)=>res.json(await game.claim(req.user.id,id.parse(req.params.id)))));
medipulsiRouter.get('/leaderboard',asyncHandler(async(req,res)=>res.json(await game.leaderboard(z.enum(['week','season']).default('week').parse(req.query.period)))));
