import React, { useState } from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import { ArrowUpRight, CalendarCheck2, HeartPulse, MessageCircle, PawPrint, Plus, Scale } from 'lucide-react-native';
import type { Pet } from '@/lib/api';
import { getSpecies } from '@/lib/petsCatalog';
import { formatPetAgeKa } from '@/lib/petsAge';
import { ka } from '@/i18n/ka';
import { useThemeColors } from '@/theme/colors';
import { PetPhoto } from './PetPhoto';
import { PetAction, PetButton, PetIntro, PetPanel, PetText } from './PetUi';
import { PetErrorText, PetFilterChip } from './PetScreen';
import { tx } from '@/i18n/locale';

export function PetsHubView({ pets, error, offline, onNavigate, onRetry }: { pets: Pet[]; error?: string | null; offline?: boolean; onNavigate: (path: string) => void; onRetry: () => void }) {
  const c = useThemeColors(), [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = pets.find(pet => pet.id === selectedId) ?? pets[0];
  return <View style={{ gap: 22 }}>
    <PetIntro title={tx('მათი პატარა სამყარო.', 'Their little world.')} body={tx('მეტი ზრუნვა, ნაკლები დავიწყება. შენი ცხოველების ამბები და ყოველდღიური მოვლა ერთ სივრცეში.', 'More care, less forgetting. Your pets’ stories and daily care in one place.')} />
    {error ? <View style={{ gap: 8 }}><PetErrorText message={error} /><PetButton label={tx('განახლება', 'Refresh')} variant="secondary" onPress={onRetry} /></View> : null}
    {!pets.length && !error ? <PetPanel><View style={{ gap: 16 }}><View style={{ width: 64, height: 64, borderRadius: 22, backgroundColor: c.accent100, alignItems: 'center', justifyContent: 'center' }}><PawPrint size={30} color={c.primary100} /></View><PetText size={21} bold>{tx('პირველი ნაბიჯი — გაცნობა.', 'First step — introductions.')}</PetText><PetText muted>{tx('დაიწყე სახელითა და სახეობით. ფოტო, ასაკი და სხვა დეტალები მოგვიანებითაც შეგიძლია დაამატო.', 'Start with a name and species. You can add a photo, age and other details later.')}</PetText><PetButton label={tx('ცხოველის დამატება', 'Add a pet')} icon={Plus} onPress={() => onNavigate('/pets/new')} /></View></PetPanel> : null}
    {pets.length ? <View style={{ gap: 12 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><PetText size={17} bold>{tx('ჩემი ცხოველები ·', 'My pets ·')} {pets.length}</PetText><Pressable accessibilityRole="button" accessibilityLabel={tx('ცხოველის დამატება', 'Add a pet')} onPress={() => onNavigate('/pets/new')} style={{ minWidth: 44, minHeight: 44, borderRadius: 16, backgroundColor: c.accent100, alignItems: 'center', justifyContent: 'center' }}><Plus size={21} color={c.primary100} /></Pressable></View>{pets.map(pet => <PetPanel key={pet.id} onPress={() => onNavigate(`/pets/${pet.id}`)}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 14 }}><PetPhoto photoUrl={pet.photoUrl} name={pet.name} size={66} /><View style={{ flex: 1, gap: 4 }}><PetText size={19} bold>{pet.name}</PetText><PetText size={12} muted>{getSpecies(pet.speciesId)?.labelKa} · {formatPetAgeKa(pet.age, ka.pets)}</PetText><PetText size={12} color={c.primary100}>{tx('პროფილი და ჩანაწერები', 'Profile and records')}</PetText></View><ArrowUpRight size={20} color={c.primary100} /></View></PetPanel>)}</View> : null}
    {selected ? <View style={{ gap: 12 }}><PetText size={17} bold>{tx('ზრუნვა ·', 'Care ·')} {selected.name}</PetText>{pets.length > 1 ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{pets.map(pet => <PetFilterChip key={pet.id} selected={selected.id === pet.id} label={pet.name} onPress={() => setSelectedId(pet.id)} />)}</ScrollView> : null}<PetAction icon={CalendarCheck2} title={tx('მოვლის კალენდარი', 'Care calendar')} body={tx('დაგეგმე პროცედურები და ნახე, რა გაქვს შესასრულებელი.', 'Plan procedures and see what’s coming up.')} onPress={() => onNavigate(`/pets/${selected.id}/care`)} /><View style={{ flexDirection: 'row', gap: 10 }}><PetAction compact icon={Scale} title={tx('წონის ჩანაწერი', 'Weight log')} body={tx('გაზომვები და ცვლილება', 'Measurements and change')} onPress={() => onNavigate(`/pets/${selected.id}/weight`)} /><PetAction compact icon={MessageCircle} title="Medi Vet" body={tx('AI დამხმარე ზრუნვაში', 'AI help with care')} onPress={() => onNavigate(`/pets/${selected.id}/chat`)} /></View>{offline ? <PetText size={12} muted>{tx('ნაჩვენებია შენახული სია. ახალი ჩანაწერისთვის ინტერნეტკავშირი დაგჭირდება.', 'Showing the saved list. You’ll need an internet connection to add a new record.')}</PetText> : null}</View> : null}
    <PetPanel><View style={{ gap: 12 }}><PetText bold>{tx('როგორ დავიწყო?', 'How do I start?')}</PetText>{[{ title: tx('01 · შექმენი პროფილი', '01 · Create a profile'), body: tx('თითოეულ ცხოველს თავისი ჩანაწერები და ისტორია აქვს.', 'Each pet has their own records and history.') }, { title: tx('02 · შეინახე და დაგეგმე', '02 · Save and plan'), body: tx('უკვე ჩატარებული პროცედურა ჩაწერე ისტორიაში, მომავალი კი მოვლის გეგმაში.', 'Log procedures already done in the history, and upcoming ones in the care plan.') }, { title: tx('03 · მიჰყევი ცვლილებებს', '03 · Follow changes'), body: tx('დაამატე წონა, ალერგიები და მდგომარეობები. საჭიროებისას ინფორმაცია ვეტერინარს გაუზიარე.', 'Add weight, allergies and conditions. Share the information with your vet when needed.') }].map(item => <View key={item.title} style={{ gap: 4 }}><PetText bold size={13} color={c.primary100}>{item.title}</PetText><PetText size={12} muted>{item.body}</PetText></View>)}<View style={{ height: 1, backgroundColor: c.bg300 }} /><PetText size={12} muted>{tx('Medi Vet ინფორმაციის გაგებაში გეხმარება. დიაგნოზისა და მკურნალობისთვის მიმართე ვეტერინარს.', 'Medi Vet helps you understand information. For diagnosis and treatment, see a vet.')}</PetText></View></PetPanel>
  </View>;
}
