(function(global){
 'use strict';
 const tabs=[['overview','მიმოხილვა'],['missions','მისიები'],['gifts','საჩუქრები'],['sessions','სესიები'],['claims','ჯილდოების გაცემა'],['config','პარამეტრები'],['audit','ჟურნალი']];
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const can=cap=>state.admin?.capabilities==null||state.admin.capabilities.includes(cap);
 let selected='overview',offset=0,filter='',rows=[],ticket=0;
 const request=(path,options)=>api('/medipulsi'+path,options);
 const date=v=>v?new Date(v).toLocaleString('ka-GE'):'—';
 const time=v=>new Date(v).toISOString().slice(0,16);
 const field=(name,label,value,type='text',extra='')=>`<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value)}" ${extra}></label>`;
 const toggle=(name,label,value)=>`<label class="mp-check"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(label)}</label>`;
 const select=(name,label,value,options)=>`<label>${esc(label)}<select name="${name}">${options.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
 const button=(action,label,extra='')=>`<button type="button" class="btn" data-mp-action="${action}" ${extra}>${esc(label)}</button>`;
 const status=value=>`<span class="mp-badge">${esc(({ACTIVE:'აქტიური',PAUSED:'პაუზა',FINISHED:'დასრულებული',PENDING:'შესამოწმებელი',APPROVED:'დადასტურებული',FULFILLED:'გაცემული',REJECTED:'უარყოფილი'})[value]||value)}</span>`;
 const table=(headers,body)=>`<div class="mp-table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}">ჩანაწერი ჯერ არ არის.</td></tr>`}</tbody></table></div>`;
 function pager(total){return `<footer class="mp-pager"><span>${total?offset+1:0}–${Math.min(offset+rows.length,total)} / ${total}</span>${offset?button('prev','წინა'):''}${offset+rows.length<total?button('next','შემდეგი'):''}</footer>`;}
 async function render(){
  const root=document.getElementById('tab-medipulsi');if(!root)return;const version=++ticket;
  root.innerHTML=`<div class="mp"><nav role="tablist" aria-label="MEDIPULSI მართვა">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${selected===id}" data-mp-tab="${id}">${label}</button>`).join('')}</nav><div class="mp-body" aria-live="polite">იტვირთება…</div></div>`;
  root.querySelectorAll('[data-mp-tab]').forEach(b=>b.onclick=()=>{selected=b.dataset.mpTab;offset=0;filter='';void render();});
  const body=root.querySelector('.mp-body');
  try{
   if(!can('MEDIPULSI_VIEW'))throw new Error('MEDIPULSI_VIEW უფლება საჭიროა.');
   const data=await request('/'+selected+(['gifts','sessions','claims','audit'].includes(selected)?`?offset=${offset}${filter?'&'+(selected==='sessions'?'phase':'status')+'='+encodeURIComponent(filter):''}`:''));if(version!==ticket)return;
   rows=data.rows||[];
   if(selected==='overview')body.innerHTML=`<header class="mp-heading"><span>MEDIPULSI · მართვის ცენტრი</span><h2>ქალაქი ნაბიჯებით იღვიძებს.</h2><p>სიარული — გლობალურად. მისიები — თბილისში. დემო შედეგები რეიტინგსა და პრიზებში არ მონაწილეობს.</p></header><div class="mp-metrics">${[['მოთამაშე',data.players],['გასეირნება',data.sessions],['აქტიური · 2 წთ',data.active],['სულ კილომეტრი',((data.totals.meters||0)/1000).toFixed(1)],['გამოქვეყნებული მისია',data.missions],['საჩუქარი',data.gifts],['მისაღები განაცხადი',data.pending],['ჯილდოს ჩანაწერი',data.claims]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join('')}</div><div class="mp-note">${data.config?.data?.enabled===false?'თამაში შეჩერებულია.':'თამაში ჩართულია.'} სესიის გაზომვები GPS-ის შეფასებაა. ფიზიკური პრიზის განაცხადი გაცემამდე შეამოწმე.</div>`;
   if(selected==='missions')body.innerHTML=`<div class="mp-toolbar"><h2>თბილისის მისიები</h2>${can('MEDIPULSI_MANAGE')?button('new','ახალი მისია'):''}</div><div class="mp-cards">${rows.map(row=>`<article><span class="mp-badge">${row.archived?'არქივი':row.published?'გამოქვეყნებული':'მონახაზი'}</span><h3>${esc(row.data.name)}</h3><p>${esc(row.data.story)}</p><small>${row.data.meters} მ · ${row.data.seconds} წმ · რადიუსი ${row.data.radius} მ</small>${can('MEDIPULSI_MANAGE')?button('edit','რედაქტირება',`data-id="${esc(row.id)}"`):''}</article>`).join('')}</div>`;
   if(selected==='gifts')body.innerHTML=`<div class="mp-toolbar"><h2>საჩუქრები</h2>${can('MEDIPULSI_MANAGE')?button('new','საჩუქრის დამატება'):''}</div><p>მარაგი მოიცავს უკვე დაჯავშნილ პრიზებს. დაჯავშნა ატომურია; უარყოფილი განაცხადის მარაგიც დაცულია და ავტომატურად აღარ გაიცემა.</p>${table(['საჩუქარი','მდებარეობა','მარაგი','პერიოდი','მდგომარეობა',''],rows.map(row=>`<tr><td><strong>${esc(row.title)}</strong><small>${row.rewardKind==='PHYSICAL'?'ფიზიკური პრიზი':'ციფრული ჯილდო'}</small></td><td>${row.latitude.toFixed(5)}, ${row.longitude.toFixed(5)}<small>პულსი ${row.pulseRadius} მ · გახსნა ${row.revealRadius} მ</small></td><td>${row.allocated} / ${row.stock}</td><td>${date(row.startsAt)}<small>${date(row.endsAt)}</small></td><td>${status(row.archived?'არქივი':row.published?'გამოქვეყნებული':'მონახაზი')}</td><td>${can('MEDIPULSI_MANAGE')?button('edit','რედაქტირება',`data-id="${esc(row.id)}"`):''}</td></tr>`).join(''))}${pager(data.total)}`;
   if(selected==='sessions')body.innerHTML=`<div class="mp-toolbar"><h2>გასეირნებების შემოწმება</h2>${select('filter','სტატუსი',filter,[['','ყველა'],['ACTIVE','აქტიური'],['PAUSED','პაუზა'],['FINISHED','დასრულებული']])}</div>${table(['ანგარიში / სესია','დრო','მანძილი','ნაბიჯები','ახალი ბილიკი','მდგომარეობა','შემოწმება'],rows.map(row=>`<tr><td><strong>${esc(row.user?.fullName||row.userId)}</strong><code>${esc(row.userId)}</code><small>${esc(row.id)}</small></td><td>${date(row.startedAt)}<small>${Math.round(row.seconds/60)} წუთი · მოძრაობა ${Math.round(row.movingSeconds/60)} წთ</small></td><td>${(row.meters/1000).toFixed(2)} კმ<small>მაქს. ${Number(row.maxSpeed||0).toFixed(1)} კმ/სთ · ${row.rejected||0} გამოტოვება</small></td><td>≈ ${Math.round(row.steps)}</td><td>${Math.round(row.newMeters)} მ</td><td>${status(row.phase)}<small>${row.excluded?'რეიტინგიდან გამორიცხულია':''}</small></td><td>${can('MEDIPULSI_REVIEW')?button('review',row.excluded?'აღდგენა':'გამორიცხვა',`data-id="${esc(row.id)}"`):''}<small>${esc(row.reviewNote)}</small></td></tr>`).join(''))}${pager(data.total)}`;
   if(selected==='claims')body.innerHTML=`<div class="mp-toolbar"><h2>ჯილდოების გაცემა</h2>${select('filter','სტატუსი',filter,[['','ყველა'],['PENDING','შესამოწმებელი'],['APPROVED','დადასტურებული'],['FULFILLED','გაცემული'],['REJECTED','უარყოფილი']])}</div>${table(['პრიზი / კოდი','ანგარიში','მიღების თარიღი','სტატუსი','მოქმედება'],rows.map(row=>`<tr><td><strong>${esc(row.reward.title)}</strong><code>${esc(row.code)}</code></td><td><strong>${esc(row.user?.fullName||row.userId)}</strong><code>${esc(row.userId)}</code></td><td>${date(row.createdAt)}</td><td>${status(row.status)}<small>${esc(row.note)}</small></td><td>${can('MEDIPULSI_REVIEW')&&['PENDING','APPROVED'].includes(row.status)?button('claim','დამუშავება',`data-id="${esc(row.id)}"`):''}</td></tr>`).join(''))}${pager(data.total)}`;
   if(selected==='config')body.innerHTML=`<h2>თამაშის პარამეტრები</h2><form class="mp-form" data-config><fieldset ${can('MEDIPULSI_MANAGE')?'':'disabled'}>${toggle('enabled','თამაში ჩართულია',data.data.enabled)}${toggle('giftsEnabled','საჩუქრები ჩართულია',data.data.giftsEnabled)}${toggle('leaderboardEnabled','რეიტინგი ჩართულია',data.data.leaderboardEnabled)}${field('message','მოთამაშისთვის შეტყობინება',data.data.message||'','text','maxlength="300"')}<p>GPS-ის ზღვარი: სიზუსტე ≤25 მ, სიჩქარე ≤7 მ/წმ, უწყვეტი ნიმუშების შუალედი ≤15 წმ. პაუზები გზას არ აერთებს. ოფლაინ ჩანაწერი მიიღება 24 საათამდე.</p><button class="btn primary" type="submit">შენახვა</button></fieldset><p role="status"></p></form>`;
   if(selected==='audit')body.innerHTML=`<h2>ცვლილებების ჟურნალი</h2>${table(['თარიღი','ადმინი','მოქმედება','ჩანაწერი','დეტალები'],rows.map(row=>`<tr><td>${date(row.createdAt)}</td><td><code>${esc(row.actorId)}</code></td><td>${esc(row.action)}</td><td><code>${esc(row.entityId)}</code></td><td><details><summary>ნახვა</summary><pre>${esc(JSON.stringify(row.details,null,2))}</pre></details></td></tr>`).join(''))}${pager(data.total)}`;
   const f=body.querySelector('[name=filter]');if(f)f.onchange=()=>{filter=f.value;offset=0;void render();};
   const cfg=body.querySelector('[data-config]');if(cfg)cfg.onsubmit=async event=>{event.preventDefault();const input=new FormData(cfg);await submit(cfg,()=>request('/config',{method:'PUT',body:{revision:data.revision,data:{enabled:input.has('enabled'),giftsEnabled:input.has('giftsEnabled'),leaderboardEnabled:input.has('leaderboardEnabled'),message:input.get('message')}}}));};
   body.querySelectorAll('[data-mp-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.mpAction,row=rows.find(r=>r.id===b.dataset.id);if(action==='prev'||action==='next'){offset+=action==='next'?50:-50;void render();}else editor(row,action);});
  }catch(e){if(version===ticket)body.innerHTML=`<div class="mp-note" role="alert">${esc(e.message)}</div>${button('retry','თავიდან ცდა')}`;body.querySelector('[data-mp-action=retry]')?.addEventListener('click',render);}
 }
 async function submit(form,task){const btn=form.querySelector('[type=submit]');btn.disabled=true;try{await task();form.closest('dialog')?.close();form.closest('dialog')?.remove();await render();}catch(e){form.querySelector('[role=status]').textContent=e.message;btn.disabled=false;}}
 function editor(row,action){
  const dialog=document.createElement('dialog');dialog.className='mp-dialog';let fields='',title='';
  if(selected==='missions'){
   const m=row?.data||{id:'',name:'',chapter:'green',center:[44.7509,41.7098],radius:200,meters:300,seconds:60,title:'',story:'',tip:'იარე საჯარო საფეხმავლო სივრცეში.',icon:'trees',source:'https://www.openstreetmap.org/'};title=row?'მისიის რედაქტირება':'თბილისის ახალი მისია';
   fields=field('id','მისიის კოდი',m.id,'text',`required pattern="[a-zA-Z0-9_-]+" ${row?'readonly':''}`)+field('name','სახელი',m.name,'text','required maxlength="100"')+select('chapter','კოლექცია',m.chapter,[['green','მწვანე თბილისი'],['oldtown','ძველი ქალაქი'],['horizon','ჰორიზონტი'],['culture','კულტურა']])+select('icon','იკონკა',m.icon,[['trees','პარკი'],['landmark','ღირშესანიშნაობა'],['waves','ტბა'],['mountain','მთა'],['bridge','ხიდი'],['flower','ბაღი']])+field('longitude','გრძედი',m.center[0],'number','step="any" min="44.5" max="45.1" required')+field('latitude','განედი',m.center[1],'number','step="any" min="41.55" max="41.9" required')+field('radius','რადიუსი · მ',m.radius,'number','min="40" max="2000" required')+field('meters','გასავლელი მანძილი · მ',m.meters,'number','min="50" max="10000" required')+field('seconds','მოძრაობის დრო · წმ',m.seconds,'number','min="60" max="7200" required')+field('title','სათაური',m.title)+field('story','ისტორია',m.story)+field('tip','ადგილზე მისვლის რჩევა',m.tip)+field('source','წყაროს HTTPS ბმული',m.source,'url','required')+toggle('published','გამოქვეყნებულია',row?.published)+toggle('archived','არქივში გადატანა',row?.archived);
  }else if(selected==='gifts'){
   const g=row||{id:crypto.randomUUID(),title:'',description:'',longitude:44.7509,latitude:41.7098,pulseRadius:120,revealRadius:20,rewardKind:'DIGITAL',stock:1,startsAt:new Date(),endsAt:new Date(Date.now()+7*86400000)};title=row?'საჩუქრის რედაქტირება':'ახალი საჩუქარი';
   fields=field('title','საჩუქრის სახელი',g.title,'text','required maxlength="100"')+field('description','აღწერა და მიღების პირობები',g.description)+select('rewardKind','პრიზის ტიპი',g.rewardKind,[['DIGITAL','ციფრული'],['PHYSICAL','ფიზიკური — ადმინის შემოწმებით']])+field('longitude','გრძედი',g.longitude,'number','step="any" min="-180" max="180" required')+field('latitude','განედი',g.latitude,'number','step="any" min="-90" max="90" required')+field('pulseRadius','პულსის დიაპაზონი · მ',g.pulseRadius,'number','min="40" max="500" required')+field('revealRadius','გახსნის რადიუსი · მ',g.revealRadius,'number','min="10" max="50" required')+field('stock','სულ მარაგი',g.stock,'number',`min="${g.allocated||0}" required`)+field('startsAt','დასაწყისი · UTC',time(g.startsAt),'datetime-local','required')+field('endsAt','დასასრული · UTC',time(g.endsAt),'datetime-local','required')+toggle('published','გამოქვეყნებულია',g.published)+toggle('archived','არქივში გადატანა',g.archived)+`<p class="mp-note">მოათავსე მხოლოდ საჯარო და უსაფრთხო საფეხმავლო ადგილზე. საჩუქრის კოორდინატები დიაპაზონამდე მომხმარებელს არ გადაეცემა.</p>`;
   row=g;
  }else if(action==='review'){title='სესიის შემოწმება';fields=`<p>${row.excluded?'რეიტინგში დაბრუნება':'რეიტინგიდან გამორიცხვა'}. გავლილი გზის პირადი ისტორია რჩება.</p>`+field('reason','მიზეზი',row.reviewNote,'text','required minlength="5" maxlength="500"');}
  else if(action==='claim'){title='ჯილდოს დამუშავება';fields=`<p>${esc(row.reward.title)} · ${esc(row.code)}</p>`+select('status','ახალი სტატუსი','',row.status==='PENDING'?[['APPROVED','დადასტურება'],['REJECTED','უარყოფა']]:[['FULFILLED','გაცემის დადასტურება'],['REJECTED','უარყოფა']])+field('reason','შემოწმების შედეგი / გაცემის შენიშვნა','','text','required minlength="5" maxlength="500"');}
  if(['missions','gifts'].includes(selected))fields='<div class="mp-map-section"><p>აირჩიე ადგილი რუკაზე ან ჩაწერე კოორდინატები.</p><div class="mp-map-picks">'+button('tbilisi','თბილისი')+(selected==='gifts'?button('world','მთელი მსოფლიო'):'')+'</div><div class="mp-map" role="region" aria-label="ადგილმდებარეობის არჩევა"></div><small class="mp-map-status"></small></div>'+fields;
  dialog.innerHTML=`<header><h2>${title}</h2><button type="button" data-close aria-label="დახურვა">×</button></header><form class="mp-form"><div class="mp-fields">${fields}</div><p role="status"></p><button type="submit" class="btn primary">შენახვა</button></form>`;document.body.appendChild(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
  if(['missions','gifts'].includes(selected))void locationPicker(dialog);
  const form=dialog.querySelector('form');form.onsubmit=event=>{event.preventDefault();const f=new FormData(form),str=n=>String(f.get(n)||''),num=n=>Number(f.get(n));void submit(form,()=>{
   if(selected==='missions'){const key=str('id');return request('/missions/'+key,{method:'PUT',body:{revision:row?.revision||0,published:f.has('published'),archived:f.has('archived'),data:{id:key,name:str('name'),chapter:str('chapter'),icon:str('icon'),center:[num('longitude'),num('latitude')],radius:num('radius'),meters:num('meters'),seconds:num('seconds'),title:str('title'),story:str('story'),tip:str('tip'),source:str('source')}}});}
   if(selected==='gifts')return request('/gifts/'+row.id,{method:'PUT',body:{revision:row.revision||0,title:str('title'),description:str('description'),longitude:num('longitude'),latitude:num('latitude'),pulseRadius:num('pulseRadius'),revealRadius:num('revealRadius'),rewardKind:str('rewardKind'),stock:num('stock'),startsAt:new Date(str('startsAt')+'Z').toISOString(),endsAt:new Date(str('endsAt')+'Z').toISOString(),published:f.has('published'),archived:f.has('archived')}});
   if(action==='review')return request('/sessions/'+row.id+'/review',{method:'PATCH',body:{excluded:!row.excluded,reason:str('reason')}});
   return request('/claims/'+row.id,{method:'PATCH',body:{status:str('status'),reason:str('reason')}});
  });};
 }

 let mapLoader;
 async function locationPicker(dialog){
  const host=dialog.querySelector('.mp-map'),status=dialog.querySelector('.mp-map-status');
  let map;
  try{
   const config=await request('/map');if(!config.token)throw new Error('რუკის გასაღები მიუწვდომელია. კოორდინატები ხელით ჩაწერე.');
   if(!global.mapboxgl){mapLoader??=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://api.mapbox.com/mapbox-gl-js/v3.14.0/mapbox-gl.js';script.onload=resolve;script.onerror=()=>{mapLoader=null;reject(new Error('რუკა ვერ ჩაიტვირთა.'));};document.head.appendChild(script);const css=document.createElement('link');css.rel='stylesheet';css.href='https://api.mapbox.com/mapbox-gl-js/v3.14.0/mapbox-gl.css';document.head.appendChild(css);});await mapLoader;}
   if(!dialog.isConnected)return;
   const lon=dialog.querySelector('[name=longitude]'),lat=dialog.querySelector('[name=latitude]'),radius=dialog.querySelector('[name=radius]')||dialog.querySelector('[name=pulseRadius]');
   const point=()=>[Number(lon.value),Number(lat.value)];
   map=new global.mapboxgl.Map({container:host,accessToken:config.token,style:'mapbox://styles/mapbox/light-v11',center:point(),zoom:15,attributionControl:true});
   const marker=new global.mapboxgl.Marker({color:'#0D9488',draggable:true}).setLngLat(point()).addTo(map);
   function draw(){if(!map.isStyleLoaded())return;const [x,y]=point(),r=Number(radius.value)||100,ring=Array.from({length:65},(_,i)=>{const a=i/64*Math.PI*2;return [x+Math.cos(a)*r/(111195*Math.cos(y*Math.PI/180)),y+Math.sin(a)*r/111195];});const data={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[ring]}};if(map.getSource('range'))map.getSource('range').setData(data);else{map.addSource('range',{type:'geojson',data});map.addLayer({id:'range-fill',type:'fill',source:'range',paint:{'fill-color':'#14B8A6','fill-opacity':.14}});map.addLayer({id:'range-border',type:'line',source:'range',paint:{'line-color':'#0D9488','line-width':2}});}}
   function update(p){lon.value=p[0].toFixed(6);lat.value=p[1].toFixed(6);marker.setLngLat(p);draw();}
   map.on('load',draw);map.on('click',e=>update([e.lngLat.lng,e.lngLat.lat]));marker.on('dragend',()=>{const p=marker.getLngLat();update([p.lng,p.lat]);});
   [lon,lat,radius].forEach(input=>input.addEventListener('change',()=>{marker.setLngLat(point());map.easeTo({center:point(),duration:300});draw();}));
   dialog.querySelector('[data-mp-action=tbilisi]').onclick=()=>{update([44.7509,41.7098]);map.flyTo({center:point(),zoom:15});};
   const world=dialog.querySelector('[data-mp-action=world]');if(world)world.onclick=()=>{map.flyTo({center:point(),zoom:2});status.textContent='აირჩიე ნებისმიერი ქვეყანა; გაადიდე რუკა და მოათავსე საჩუქარი საჯარო ბილიკზე.';};
   dialog.addEventListener('close',()=>map.remove(),{once:true});status.textContent='პინი გადაადგილდება შეხებით ან გადათრევით.';
  }catch(e){status.textContent=e.message;}
 }
 global.renderMedipulsi=render;
 // The restored tab can be selected before this deferred module is registered.
 if(typeof state!=='undefined'&&state.admin&&state.tab==='medipulsi')void render();
})(window);
