// Collects MEDICARD's graphic files into brand/brandbook/manifest.js for the brand book page.
//   node brand/brandbook/build.mjs
// Paths in the manifest are relative to brand/brandbook/ (the page links the real files — nothing is copied).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../..');
const rel = (p) => path.relative(here, path.join(root, p)).split(path.sep).join('/');
const IMG = /\.(png|jpe?g|webp|svg)$/i;

function list(dir, filter = () => true) {
  const abs = path.join(root, dir);
  if (!fs.existsSync(abs)) return [];
  return fs
    .readdirSync(abs)
    .filter((f) => IMG.test(f) && filter(f))
    .sort()
    .map((f) => ({ src: rel(`${dir}/${f}`), name: f.replace(IMG, '').replace(/[-_]/g, ' ') }));
}

const groups = [
  { id: 'quest', title: 'MEDIQUEST', note: 'მისიები, ჯილდოები და ოთახის დეკორი', items: list('mobile/assets/art/quest') },
  { id: 'run', title: 'MEDIRUN', note: 'რუკის ხატულები, საჩუქრები და თბილისის მისიები', items: [...list('mobile/assets/run'), ...list('mobile/assets/run/icons'), ...list('mobile/assets/run/missions')] },
  { id: 'pets', title: 'MEDIVET', note: 'ცხოველები და მოვლა', items: list('mobile/assets/art/pets') },
  { id: 'rewards', title: 'Medi Coins მაღაზია', note: 'საჩუქრების რენდერები, ლოგოს გარეშე', items: [...list('mobile/assets/art', (f) => f.startsWith('coin')), ...list('server/public/rewards')] },
  { id: 'empty', title: 'ცარიელი ეკრანები და მიზნები', note: 'empty states, ონბორდინგის მიზნები, მოწვევა', items: [...list('mobile/assets/art/empty'), ...list('mobile/assets/art/goal'), ...list('mobile/assets/art/referral')] },
  { id: 'pregnancy', title: 'ორსულობა', note: 'ნაყოფის ზომა და განვითარება კვირების მიხედვით', items: [...list('mobile/assets/pregnancy-size'), ...list('mobile/assets/pregnancy-development')] },
  { id: 'figma', title: 'Figma ილუსტრაციები', note: 'განწყობა, სხეული, ონბორდინგი (Nightingale UI kit)', items: [...list('mobile/assets/figma/illustrations'), ...list('mobile/assets/figma/welcome')] },
  { id: 'reactions', title: 'ქალების სივრცის რეაქციები', note: 'ანიმირებული რეაქციების სტატიკური კადრები', items: list('mobile/assets/community/reactions') },
];

// Cycle logging glyphs (Health Icons, MIT) — the generated TS module holds the SVG strings.
const iconTs = fs.readFileSync(path.join(root, 'mobile/src/constants/cycleIconSvg.ts'), 'utf8');
const cycleIcons = {};
for (const m of iconTs.matchAll(/^\s{2}([a-zA-Z0-9_]+): "((?:[^"\\]|\\.)*)",?$/gm)) cycleIcons[m[1]] = JSON.parse(`"${m[2]}"`);

const social = list('brand', (f) => /^(facebook-(cover|profile)(-circle)?|social-(post|hook|editorial)-[a-z-]+)\.png$/.test(f) && !/preview|-v\d/.test(f));

const manifest = { generated: new Date().toISOString().slice(0, 10), groups, cycleIcons, social };
fs.writeFileSync(path.join(here, 'manifest.js'), `// Generated by build.mjs — do not edit.\nwindow.BRANDBOOK = ${JSON.stringify(manifest, null, 1)};\n`);
const count = groups.reduce((n, g) => n + g.items.length, 0);
console.log(`${count} illustrations in ${groups.length} groups, ${Object.keys(cycleIcons).length} cycle icons, ${social.length} social files`);
