// Builds mobile/src/constants/cycleIconSvg.ts from Health Icons (MIT, https://healthicons.org — vendored
// copies of the few files we use live in brand/cycle/icons/src with the licence). One flat glyph family,
// 48×48 viewBox, `currentColor` fills, so the app tints each tile by its group ink.
//
//   node build.mjs [path/to/healthicons/public/icons/svg]   (default: scratch copy; files already in src/ are reused)
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, 'src');
const OUT = join(here, '..', '..', '..', 'mobile', 'src', 'constants', 'cycleIconSvg.ts');
const PACK = process.argv[2] || 'C:/Users/User/AppData/Local/Temp/claude/C--Users-User-Desktop-www-medicard/040e13a6-6e04-40b2-87a3-e337184422b0/scratchpad/hi/package/public/icons/svg';
mkdirSync(SRC, { recursive: true });

/** glyph key → Health Icons path (filled set). Several log ids share one glyph (see GLYPH_FOR in the app). */
const GLYPHS = {
  drop: 'body/blood_drop',
  uterus: 'body/female_reproductive_system',
  belly: 'conditions/intestinal-pain',
  back: 'conditions/back_pain',
  head: 'conditions/headache',
  breasts: 'body/breasts',
  pain: 'conditions/pain',
  stomach: 'body/stomach',
  nausea: 'conditions/nausea',
  vomiting: 'conditions/vomiting',
  diarrhea: 'conditions/diarrhea',
  intestine: 'body/intestine',
  colon: 'body/colon',
  chills: 'conditions/chills',
  sweating: 'conditions/sweating',
  fever: 'emotions/fever',
  dizzy: 'emotions/dizzy',
  sleepy: 'emotions/sleepy',
  woozy: 'emotions/woozy',
  coughing: 'emotions/coughing',
  joints: 'body/joints',
  arm: 'body/arm',
  leg: 'body/leg',
  skin: 'body/body',
  water: 'objects/running_water',
  nose: 'body/nose',
  ear: 'body/ear',
  heartbeat: 'symbols/heartbeat',
  lungs: 'body/lungs',
  bladder: 'body/bladder',
  female: 'symbols/female',
  discharge: 'symbols/discharge',
  meal: 'nutrition/hot_meal',
  sugar: 'nutrition/sugar',
  thermometer: 'devices/thermometer',
  alcohol: 'nutrition/alcohol',
  running: 'exercise/running',
  bars: 'symbols/high_bars',
  yes: 'symbols/yes',
  rdt: 'diagnostics/rdt_result',
  rdtPositive: 'diagnostics/rdt_result_positive',
  // moods
  calm: 'emotions/calm',
  happy: 'emotions/happy',
  ok: 'emotions/ok',
  neutral: 'emotions/neutral',
  nervous: 'emotions/nervous',
  angry: 'emotions/angry',
  sad: 'emotions/sad',
  crying: 'emotions/crying',
  confused: 'emotions/confused',
  notOk: 'emotions/not_ok',
  nauseous: 'emotions/nauseous',
  sweatingFace: 'emotions/sweating',
  tongue: 'emotions/tongue',
};

const lines = ['// Generated by brand/cycle/icons/build.mjs from Health Icons (MIT) — do not edit by hand.', '// Flat 48×48 glyphs with `currentColor` fills; `CycleIconTile` tints them by group ink.', '', 'export const CYCLE_ICON_SVG = {'];
for (const [key, rel] of Object.entries(GLYPHS)) {
  const local = join(SRC, `${key}.svg`);
  if (!existsSync(local)) copyFileSync(join(PACK, 'filled', `${rel}.svg`), local);
  let svg = readFileSync(local, 'utf8').replace(/\r?\n/g, '').replace(/>\s+</g, '><').replace(/\s{2,}/g, ' ').trim();
  if (!svg.includes('currentColor')) throw new Error(`${key}: no currentColor in ${rel}`);
  lines.push(`  ${key}: ${JSON.stringify(svg)},`);
}
lines.push('} as const;', '', 'export type CycleIconGlyph = keyof typeof CYCLE_ICON_SVG;', '');
writeFileSync(OUT, lines.join('\n'));
if (!existsSync(join(SRC, 'LICENSE'))) copyFileSync(join(PACK, '..', '..', '..', 'LICENSE'), join(SRC, 'LICENSE'));
console.log('wrote', OUT, Object.keys(GLYPHS).length, 'glyphs');
