import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
// Fail closed: this suite NEVER reads the hosted .env database URL.
const url=process.env.MEDIPULSI_TEST_DATABASE_URL;
if(!url||new URL(url).hostname!=='127.0.0.1'||!new URL(url).pathname.endsWith('_test'))throw new Error('Set MEDIPULSI_TEST_DATABASE_URL to the disposable local *_test database.');
process.env.DATABASE_URL=url;process.env.NODE_ENV='test';process.env.JWT_SECRET='medipulsi-disposable-test-secret-only';process.env.EVIDENCEMD_API_KEY='unused-test';
const [{default:express},{default:jwt},{prisma},{medipulsiRouter},{adminMedipulsiRouter},{MISSIONS}]=await Promise.all([import('express'),import('jsonwebtoken'),import('../src/lib/prisma.js'),import('../src/routes/medipulsi.routes.js'),import('../src/routes/adminMedipulsi.routes.js'),import('../src/lib/medipulsi/core/missions.js')]);
const app=express();app.use(express.json());app.use('/api/medipulsi',medipulsiRouter);app.use('/api/admin/medipulsi',adminMedipulsiRouter);app.use((e,req,res,next)=>res.status(e.status||(e.name==='ZodError'?400:500)).json({error:e.message,code:e.code}));
const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
const userIds=[],adminIds=[],giftIds=[],auditActors=[];
after(async()=>{await prisma.medipulsiAudit.deleteMany({where:{actorId:{in:adminIds}}});await prisma.user.deleteMany({where:{id:{in:userIds}}});await prisma.medipulsiGift.deleteMany({where:{id:{in:giftIds}}});await prisma.admin.deleteMany({where:{id:{in:adminIds}}});server.close();await prisma.$disconnect();});
async function user(status='ACTIVE'){const id=randomUUID();userIds.push(id);await prisma.user.create({data:{id,email:id+'@medipulsi.test',passwordHash:'no-login-test',fullName:'Disposable tester',status}});return {id,token:jwt.sign({sub:id},process.env.JWT_SECRET)};}
async function admin(capabilities){const id=randomUUID();adminIds.push(id);await prisma.admin.create({data:{id,email:id+'@medipulsi.test',passwordHash:'no-login-test',fullName:'Disposable admin',capabilities}});return {id,token:jwt.sign({sub:id,role:'admin'},process.env.JWT_SECRET)};}
async function request(who,path,method='GET',body,adminMode=false){const r=await fetch(origin+'/api/'+(adminMode?'admin/':'')+'medipulsi'+path,{method,headers:{'Content-Type':'application/json',...(who?{Authorization:'Bearer '+who.token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()};}
async function walk(who,start=[5.5797,50.6326],count=15){
 const id=randomUUID();assert.equal((await request(who,'/sessions','POST',{id})).status,200);const now=Date.now();await prisma.medipulsiSession.update({where:{id},data:{startedAt:new Date(now-120000)}});
 const fixes=Array.from({length:count},(_,i)=>({position:[start[0]+i*.00006,start[1]],accuracy:5,timestamp:now-(count-i)*4000,speed:1.1}));const batch={id:randomUUID(),seq:1,fixes};assert.equal((await request(who,`/sessions/${id}/batches`,'POST',batch)).status,200);return {id,batch,fixes};
}
test('MEDIPULSI real database integration',async t=>{
 const a=await user(),b=await user(),blocked=await user('BLOCKED'),viewer=await admin(['MEDIPULSI_VIEW']),manager=await admin(['MEDIPULSI_VIEW','MEDIPULSI_MANAGE','MEDIPULSI_REVIEW']);
 await t.test('requires the existing ACTIVE account and rejects admin tokens',async()=>{assert.equal((await request(null,'/bootstrap')).status,401);assert.equal((await request(blocked,'/bootstrap')).status,403);assert.equal((await request(manager,'/bootstrap')).status,403);});
 await t.test('bootstraps a separate account and Tbilisi catalog without duplicating User',async()=>{const r=await request(a,'/bootstrap');assert.equal(r.status,200);assert.equal(r.data.userId,a.id);assert.equal(r.data.missions.length,24);assert.equal(r.data.state.journey.source,'gps');assert.ok(r.data.missions.every(m=>m.center[0]>44.5&&m.center[1]<42));});
 await t.test('walking works in New York, Sydney and Tokyo without Tbilisi stamps',async()=>{for(const point of [[-73.97,40.77],[151.20,-33.86],[139.76,35.68]]){const person=await user();await request(person,'/bootstrap');const trip=await walk(person,point);const data=(await request(person,'/bootstrap')).data;assert.ok(data.state.journey.meters>40);assert.ok(data.state.journey.trail.length);assert.equal(Object.keys(data.state.book.progress).length,0);await request(person,`/sessions/${trip.id}/finish`,'POST');}});
 let w;
 await t.test('Liège walking persists distance, steps and trace without Tbilisi completion',async()=>{await request(a,'/mission','PUT',{id:'vake'});w=await walk(a);const r=(await request(a,'/bootstrap')).data;assert.ok(r.state.journey.meters>40);assert.ok(r.state.journey.steps>50);assert.ok(r.state.journey.trail.length);assert.equal(Object.keys(r.state.journey.covered).length,0);assert.equal(Object.keys(r.state.book.progress).length,0);});
 await t.test('retry is idempotent and altered retries are rejected',async()=>{const before=(await request(a,'/bootstrap')).data.state.journey.meters;assert.equal((await request(a,`/sessions/${w.id}/batches`,'POST',w.batch)).status,200);const altered={...w.batch,fixes:w.batch.fixes.slice(1)};assert.equal((await request(a,`/sessions/${w.id}/batches`,'POST',altered)).status,409);assert.equal((await request(a,'/bootstrap')).data.state.journey.meters,before);});
 await t.test('another account cannot write, pause, or claim the session',async()=>{assert.equal((await request(b,`/sessions/${w.id}/pause`,'POST')).status,404);assert.equal((await request(b,`/sessions/${w.id}/batches`,'POST',w.batch)).status,404);const other=(await request(b,'/bootstrap')).data;assert.equal(other.state.journey.meters,0);assert.equal(other.state.journey.trail.length,0);});
 await t.test('the client cannot submit totals or demo progress',async()=>{assert.equal((await request(a,`/sessions/${w.id}/batches`,'POST',{...w.batch,id:randomUUID(),seq:2,meters:9999})).status,400);assert.equal((await request(a,'/settings','PATCH',{points:999})).status,400);});
 await t.test('parallel sequences serialize, only one can add progress',async()=>{const f={position:[5.5806,50.6326],accuracy:5,timestamp:Date.now()-500,speed:1};const results=await Promise.all([1,2].map(()=>request(a,`/sessions/${w.id}/batches`,'POST',{id:randomUUID(),seq:2,fixes:[f]})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
 await t.test('pause and finish preserve colored history and disconnect the GPS anchor',async()=>{assert.equal((await request(a,`/sessions/${w.id}/pause`,'POST')).status,200);const paused=(await request(a,'/bootstrap')).data;assert.equal(paused.state.journey.lastFix,null);assert.equal(paused.session.phase,'PAUSED');assert.ok(paused.state.journey.trail.length);assert.equal((await request(a,`/sessions/${w.id}/batches`,'POST',{id:randomUUID(),seq:3,fixes:w.fixes.slice(0,1)})).status,409);assert.equal((await request(a,`/sessions/${w.id}/finish`,'POST')).status,200);const done=(await request(a,'/bootstrap')).data;assert.equal(done.session,null);assert.equal(done.state.journey.meters,0);assert.ok(done.state.journey.trail.length);assert.equal(done.history[0].id,w.id);});
 await t.test('settings and private-by-default ranking are persisted',async()=>{const r=await request(a,'/settings','PATCH',{theme:'light',handle:'ლიეჟის მკვლევარი',leaderboardOptIn:true});assert.equal(r.data.settings.theme,'light');assert.equal(r.data.handle,'ლიეჟის მკვლევარი');assert.equal((await request(b,'/bootstrap')).data.leaderboardOptIn,false);const rows=(await request(a,'/leaderboard')).data.rows;assert.equal(rows.length,1);assert.equal(rows[0].handle,'ლიეჟის მკვლევარი');assert.ok(rows[0].meters>40);assert.equal(rows[0].newMeters,0);await request(a,'/settings','PATCH',{leaderboardOptIn:false});assert.deepEqual((await request(a,'/leaderboard')).data.rows,[]);});
 const wa=await walk(a),wb=await walk(b);const pos=wa.fixes.at(-1).position;
 const gid=randomUUID();giftIds.push(gid);
 await t.test('admin capabilities gate writes and validate gift parameters',async()=>{const body={title:'საცდელი ყუთი',description:'Disposable prize',longitude:pos[0],latitude:pos[1],pulseRadius:120,revealRadius:20,rewardKind:'PHYSICAL',stock:1,published:true,archived:false,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+600000).toISOString(),revision:0};assert.equal((await request(viewer,'/gifts/'+gid,'PUT',body,true)).status,403);assert.equal((await request(manager,'/gifts/'+gid,'PUT',body,true)).status,200);assert.equal((await request(a,'/gifts', 'GET',undefined,true)).status,403);});
 await t.test('gift discovery reveals coordinates only inside the reveal radius',async()=>{const p=await prisma.medipulsiPlayer.findUnique({where:{userId:a.id}});const state=structuredClone(p.state);state.journey.position=[pos[0]-.0008,pos[1]];await prisma.medipulsiPlayer.update({where:{userId:a.id},data:{state}});const signal=(await request(a,'/nearby')).data;assert.equal(signal.signal,true);assert.equal(signal.revealed,false);assert.equal(signal.gift,null);await prisma.medipulsiPlayer.update({where:{userId:a.id},data:{state:p.state}});const revealed=(await request(a,'/nearby')).data;assert.equal(revealed.gift.id,gid);assert.equal(revealed.revealed,true);});
 let winner,claim;
 await t.test('one-item inventory cannot be over-claimed by simultaneous users',async()=>{const results=await Promise.all([request(a,`/gifts/${gid}/claim`,'POST'),request(b,`/gifts/${gid}/claim`,'POST')]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const index=results.findIndex(r=>r.status===200);winner=[a,b][index];claim=results[index].data;assert.equal(claim.status,'PENDING');assert.equal((await prisma.medipulsiGift.findUnique({where:{id:gid}})).allocated,1);});
 await t.test('repeat claim returns the same receipt, without reserving again',async()=>{const repeat=await request(winner,`/gifts/${gid}/claim`,'POST');assert.equal(repeat.data.id,claim.id);assert.equal((await prisma.medipulsiGift.findUnique({where:{id:gid}})).allocated,1);});
 await t.test('physical prize approval, fulfillment, and audit are enforced',async()=>{assert.equal((await request(manager,'/claims/'+claim.id,'PATCH',{status:'FULFILLED',reason:'test fulfillment'},true)).status,409);assert.equal((await request(manager,'/claims/'+claim.id,'PATCH',{status:'APPROVED',reason:'GPS and eligibility reviewed'},true)).status,200);assert.equal((await request(manager,'/claims/'+claim.id,'PATCH',{status:'FULFILLED',reason:'received with verified code'},true)).status,200);assert.equal((await request(manager,'/claims/'+claim.id,'PATCH',{status:'REJECTED',reason:'invalid late change'},true)).status,409);assert.ok((await request(manager,'/audit','GET',undefined,true)).data.rows.some(row=>row.action==='CLAIM_REVIEW'));});
 await t.test('mocked or stale GPS is not credited',async()=>{const state=(await request(b,'/bootstrap')).data.state.journey;const meter=state.meters;const input={id:randomUUID(),seq:2,fixes:[{position:[5.6,50.63],accuracy:5,timestamp:Date.now(),speed:1,mocked:true},{position:[5.6,50.63],accuracy:5,timestamp:Date.now()-90000000,speed:1}]};assert.equal((await request(b,`/sessions/${wb.id}/batches`,'POST',input)).status,200);assert.equal((await request(b,'/bootstrap')).data.state.journey.meters,meter);});
 await t.test('review exclusion is audited and has no effect on medical/User fields',async()=>{assert.equal((await request(viewer,`/sessions/${wa.id}/review`,'PATCH',{excluded:true,reason:'test review'},true)).status,403);assert.equal((await request(manager,`/sessions/${wa.id}/review`,'PATCH',{excluded:true,reason:'GPS review required'},true)).status,200);const original=await prisma.user.findUnique({where:{id:a.id}});assert.equal(original.fullName,'Disposable tester');assert.equal(original.passwordHash,'no-login-test');assert.equal(original.points,0);});
});
